= Add new information requirements

== Submit an issue:
To propose new information requirement(s), please **submit** an issue by link:https://github.com/eprocurementontology/eprocurementontology/labels/New%20information%20requirement[**clicking here**]. And then click on "**New issue**".

**Replace the text** of the default template (first row and first column) by the text of the table below:

|============================================================
|*Element*|*Description*
|ID|Identifier, short string to be used as reference to the requirement, for example R1, R2.
|Description|Description of the requirement, using keywords such as MUST, COULD and SHOULD.
|Related Use Case|In the context of the e-procurement ontology, requirements are directly linked to use cases. Therefore, it is useful to indicate to which use case(s) the requirement is related, e.g. “UC1”.
|============================================================
And then **fill the table** with your input by following the guidelines provided in the table above (second column).

Find a list of issues related to this topic by link:https://github.com/eprocurementontology/eprocurementontology/labels/New%20information%20requirement[**clicking here**].