[[header]]
= eProcurement Ontology Development Documentation

This page provides documentation useful for the ontology developers and the domain experts from the working group. This development section of the eProcurement ontology documentation provides access to versions of the conceptual model that are either in development or have been worked on currently or previously.

The ontology is hosted in GitHub repository **https://github.com/OP-TED/ePO[OP-TED/ePO^]**. The latest development is available in the _master_ branch.
The ontology documentation is published on the unified **https://docs.ted.europa.eu/[TED Developers Docs^]** website. The source of that ontology documentation is hosted in GitHub repository **https://github.com/OP-TED/epo-docs[OP-TED/epo-docs^]**.

== Conceptual model Diagrams

* HTML views for each ePO module:

** link:{attachmentsdir}/html_reports/development/ePO/index.html[ePO core]
** link:{attachmentsdir}/html_reports/development/eCatalogue/index.html[eCatalogue]
** link:{attachmentsdir}/html_reports/development/eNotice/index.html[eNotice]
** link:{attachmentsdir}/html_reports/development/eOrdering/index.html[eOrdering]
** link:{attachmentsdir}/html_reports/development/eFulfilment/index.html[eFulfilment]

* link:https://github.com/OP-TED/ePO/blob/master/analysis_and_design/conceptual_model/ePO_CM.eap[Enterprise Architect file]

