:doctitle: User's Guide to ePO
:doccode: epo-main-prod-008
:author: AD
:authoremail: achilles.dougalis@meaningfy.ws
:docdate: May 2024
:sectnums:
:toc:
:toclevels: 4
:toc-title: Contents

= Git usage methodology

:toc:
:toc-placement: preamble
:toclevels: 1
:showtitle:

toc::[]

This document is a guide to how the eProcurement Ontology can be used.

== Introduction

The ePO Ontology describes the data used in the EU public procurement process and is a
semantic data specification. The ultimate objective of the ontology is to put forth a
commonly agreed OWL ontology that will conceptualise, formally encode and make available
in an open, structured and machine-readable format data about public procurement, covering
it from end to end, i.e. from notification, through tendering to awarding, ordering,
invoicing and payment. With this goal in mind the OP engaged a Working Group (WG) of
experts with the mission of building consensus on the analysis results and deliverables
developed by the OP’s teams.


Specifically, ePO describes a set of concepts and their relations. ePO concepts can be:
Classes (objects).
Class hierarchies and dependencies.
Roles, attributes, properties, relationships, and actions.


== The ePO modules

== The ePO conceptual model

=== UML diagrams
==== What is UML
==== Ontology Representation
==== Conceptual model usage (HTML)
==== Enterprise Architect usage
==== Examples

=== Glossaries
==== Glossaries overview
==== Examples

== The ePO Implemetation

=== The OP-TED/ ePO Github repository
==== ePO modules
Mention the rest of the artefacts here and how they interelate. (restrictions)

==== SHACL shapes

== Querying the Ontology
=== ePO SPARQL endpoint

