== *eProcurement Ontology overview*

=== Abstract

_In 2016 the https://publications.europa.eu/en/home[Publications Office of the European Union] (Publications Office or OP) started a project funded by the https://ec.europa.eu/isa2/home_en[ISA Programme] to organise and support the development of a Public Procurement Ontology (ePO)._

_The ultimate objective of the ontology is to put forth a commonly agreed OWL ontology that will conceptualise, formally encode and make available in an open, structured and machine-readable format data about public procurement, covering it from end to end, i.e. from notification, through tendering to awarding, ordering, invoicing and payment. With this goal in mind the OP engaged a Working Group (WG) of experts with the mission of building consensus on the analysis results and deliverables developed by the OP’s teams._

_By mid-2017 a version 1.00 of the Ontology was delivered and submitted to the Working group for discussion. All the materials related to this version were made public and are accessible through the ISA2 https://joinup.ec.europa.eu/solution/eprocurement-ontology[Joinup] platform; including the discussions held in the Working Group (WG)._

_A new stage of the development, identified as ePO v2.0.0, was initiated in January 2018. The goal of this new version is to improve and extend the previous version._

_This document describes the objectives, the methodological approach and the deliverables produced in this new version._

=== Context

Given the increasing importance of data standards for e-Procurement, a number of initiatives driven by the public sector, the industry and academia have been launched in the recent years. Some have grown organically, while others are the result of standardisation work. The vocabularies and the semantics that they are introducing, the phases of public procurement they are covering, and the technologies they are using vary greatly amongst themselves. These differences hamper data interoperability and their reuse.

This situation creates the need for a common representation of the knowledge about the eProcurement domain as it is understood and practiced in the European Union. For this to happen a common vocabulary, axioms and rules are needed.

This document describes the work carried out by the Publications Office and the working group to develop the "eProcurement Ontology" (henceforth referred to as the ePO).

In the framework of this project, we will identify and give examples of each step of the process for creating the e-procurement ontology. Clearly specifying the roles of the different actors and the input required of them within the timeline of creating the ontology. The different phases needed to create the ontology and the intermediary processes within these phases will be clearly defined giving examples taken from the 3 use cases. In parallel to this process, a working group composed of stakeholders from multiple interested groups will be set up. This working group will decide by consensus on how the ontology should be developed at all stages and may decide to adopt the first draft of the specification proposed and described during the first meeting. This project will provide the working group with the process, methodology and technology to be followed for developing the final version of the e-procurement ontology.
