:doctitle: eProcurement Ontology Documentation
:doccode: epo-main-prod-001
:author: PWC adapted by NPJ
:authoremail: nicole-anne.paterson-jones@ext.ec.europa.eu
:docdate: June 2023

[underline]#What it is:#
The eProcurement Ontology (ePO) is a semantic ontology related to EU public procurement.

[underline]#What it does:#
ePO is a tool that conceptualizes, formally encodes and provides structured data about public procurement in both human and machine-readable formats according to EU regulations and directives.

[underline]#Scope:#
ePO covers public Procurement from end to end, i.e. from notification, to tendering to awarding, ordering, invoicing and payment.

[underline]#How:#
In order to build and maintain the ontology, OP engaged a Working Group (WG) of experts with the mission of building consensus on the analysis results and deliverables developed by the OP’s teams.





[underline]#Where to start from:#

* Introductory course on EPO
* xref:epo-home::guide.adoc[User's Guide to ePO]

The following topics are included in this version of the eProcurement Ontology documentation:


== General Documentation

* xref:epo-home::guide.adoc[User's Guide to ePO] +
A short user's guide of the ePO project
* xref:EPO::conceptual.adoc[Conceptual Models] +
The release specific conceptual Model(s) of the ontology.
* xref:EPO::glossaries.adoc[Glossaries] +
The release specific glossaries
* xref:EPO::release-notes.adoc[Release Notes] +
The release notes as on GitHub


== Reference Documentation


* xref:epo-home::methodology2024.adoc[Methodology] +
The ePO Methodology

* xref:epo-home::versioning.adoc[ePO Versioning Rules] +
An overview of the versioning rules for releases

* xref:epo-home::stories.adoc[User Stories and Natural Language Statements] +
Ontology Requirements Specification Documents (ORSD), containing user stories and natural language statements used when developing new modules.

** xref:epo-home::stories_eAccess.adoc[eAccess (ESPD Request)] +
ORSD for eAccess module
** xref:epo-home::stories_eSubmission.adoc[eSubmission (ESPD Response)] +
ORSD for eSubmission module

* xref:epo-home::governance.adoc[Other Reference Documents] +
Useful reference documents in the development of the ePO

* xref:epo-home::history.adoc[History and Planned Developments] +
Milestones in the project and future development plans

== Working Group Documents
* xref:epo-wgm::wider.adoc[Quarterly Meetings] +
Minutes, Presentations etc from the quarterly Working Group Meetings
* xref:epo-wgm::cumulative.adoc[Cumulative Reports (by year)] +
All weekly meetings minutes collated into yearly documents
* xref:epo-wgm::indiv.adoc[Individual Meeting Reports] +
All the weekly meeting minutes and documents saved individually
