:doctitle: eProcurement Ontology Documentation
:doccode: epo-main-prod-001
:author: PWC adapted by NPJ
:authoremail: nicole-anne.paterson-jones@ext.ec.europa.eu
:docdate: June 2023

[underline]#What it is:#
The eProcurement Ontology (ePO) is a semantic ontology related to EU public procurement.

[underline]#What it does:#
ePO is a tool that conceptualizes and formally encodes structured data about public procurement in both human and machine-readable formats according to EU regulations and directives.


[underline]#Where to start from:#
xref:epo-home::guide.adoc[User's Guide to ePO]

The following topics are included in this version of the eProcurement Ontology documentation:


== General Documentation

* xref:EPO::business.adoc[Business Overview] +
A short Business Overview of the ePO project
* xref:EPO::conceptual.adoc[Conceptual Models] +
The release specific conceptual Model(s) of the ontology.
* xref:EPO::glossaries.adoc[Glossaries] +
The release specific glossaries
* xref:EPO::release-notes.adoc[Release Notes] +
The release notes as on GitHub


== Reference Documentation
* xref:epo-home::references.adoc[Reference Documentation] +
Useful reference documents in the development of the ePO
* xref:epo-home::history.adoc[History and Planned Developments] +
Milestones in the project and future development plans
* xref:epo-home::methodology2024.adoc[ePO Methodology] +
The ePO Methodology
* xref:epo-home::stories.adoc[User Stories and Natural Language Statements] +
User Stories and Natural Language Statements used when developing new modules
* xref:epo-home::versioning.adoc[ePO Versioning Rules] +
An overview of the versioning rules for releases

== Working Group Documents
* xref:epo-wgm::wider.adoc[Quarterly Meetings] +
Minutes, Presentations etc from the quarterly Working Group Meetings
* xref:epo-wgm::cumulative.adoc[Cumulative Reports (by year)] +
All weekly meetings minutes collated into yearly documents
* xref:epo-wgm::indiv.adoc[Individual Meeting Reports] +
All the weekly meeting minutes and documents saved individually
