= eProcurement Ontology Documentation

[.tile-container]
--

[.tile]
.ePO V3.1.0: Latest Production Release
****
The eProcurement Ontology V3.1.0 was released on the 16 December 2022 introducing a new module, eOrdering,a combined glossary, updates, and various fixes as planned for the 2022 Q4 milestone.

xref:index_epo_3.1.0.adoc[Click here to read the version 3.1.0 details]

****

[.tile]
.ePO Future Releases
****
Information on future releases planned for the eProcurement Ontology can be found via the link below. Information includes scheduled releases in the short term, and features, updates and fixes to be addressed in the longer term.

xref:future_releases@EPO::index.adoc[Information on future releases can be found here.]
****


[.tile]
.Working Group Documents
****
This section contains minutes and reports of the Working Group activities and meetings listed by interest/ category.

xref:master@epo-wgm::index.adoc[Click here to read the working group documents]
****

[.tile]
.Model to Owl Documentation
****
The Model to Owl Project consists of a set of tools for transforming a UML v2.5 model from its XMI v2.5.1 serialisation into a formal ontology.

//xref:xxx@EPO::index.adoc[update when ready]
*update when ready*
****
--