= ePO Workflow Documentation



== Introduction and content of the documentation
or

== How to create a new eProcurement Ontology release: processes, tasks, tools, and players

The ePO Workflow documentation describes what needs to be done, and who does it, when creating a new eProcurement Ontology (ePO) release. 

Firstly it defines an end-to-end procedure. This is illustrated using diagrams created in a third party software tool specifically chosen for making visualisation of the workflows easier. 
//called http://www.hosiaisluoma.fi/ArchiMate-Cookbook.pdf[ArchiMate]. 

Then, the workflow stages are described listing the artefacts produced along the way; The criteria for transitions are defined, as are the the different roles and responsibilities of stakeholders involved in the process, as well as which supporting tools are employed e.g., xref:GitHub repositories/githubRepositories.adoc[GitHub]. 

The automation points, release note contents, and release tagging conventions are also described. Although the documentation covers everything related to the ePO lifecycle, it doesn't cover how to use the tools and technologies used in the process such as https://docs.ted.europa.eu/M2O/latest/index.html[Model2Owl]. It is assumed that you already know how to use them. However, all the inputs and outputs of these technologies in the process are clearly documented.

This documentation contains a comprehensive reference and also a step-by-step guide, capturing the stages of the workflow from the perspective of Enterprise Architecture. 

NOTE: Enterprise Architecture is a business function concerned with the structures and behaviours of a business, especially business roles and processes that create and use business data. 

You therefore have a process to follow, and a reference guide that you can use to look up anything that you need clarification on. By going through the documentation systematically via the left-hand menu, you will gain a complete understanding of the methodology, roles, artefacts, and systems that form the ePO lifecycle from planning through to release.

The methodology used, and some tips on how to read the ePO Workflow Documentation can be found xref:methodology/methodologyIndex.adoc[here].


