:doctitle: eProcurement Ontology Documentation
:doccode: epo-v3.1.0-prod-001
:author: NPJ
:authoremail: nicole-anne.paterson-jones@ext.ec.europa.eu
:docdate: June 2023

====
*Temporary explanation of intended changes:*

. Branch Nicole_refactoring merge with and become v3.1.0
. Branch new_ main will merge with and become main. This branch will contain all info that is version independent.
. Branch wg_corrections will merge with and become wg-meetings
. A new branch for the next release, now v4.0.0-rc.1 will be prepared in the background by the contractors: the release overview and release notes and typically go live with the code (except for this time when it will be later)

. A new branch "future_releases" will contain two "sets" of info regarding future dev plans: general info of what is expected in the next numbered release: fixes/ features etc, and info regarding planned work that is not yet in a release bundle (in a list or table).
. There will be a link to the model2Owl documentation from this page once the documents are ready.
. Branch v3.1.1 will be archived or deleted.
====

[.tile-container]
--

[.tile]
.ePO V3.1.0: Latest Production Release
****
The eProcurement Ontology V3.1.0 was released on the 16 December 2022 introducing a new module, eOrdering,a combined glossary, updates, and various fixes as planned for the 2022 Q4 milestone.

xref:Overview_V3.1.0.adoc[Click here to read the version 3.1.0 details]

****

[.tile]
.ePO Future Releases (to be hidden until content ready)
****
Information on future releases planned for the eProcurement Ontology can be found via the link below. Information includes scheduled releases in the short term, and features, updates and fixes to be addressed in the longer term.

xref:future_releases@EPO::Overview_v4.0.0-rc.1.adoc[Information on future releases can be found here.]
****

[.tile]
.ePO Past Releases
****
Information on past releases, versions 1.0.0 through to 3.0.1, of the eProcurement Ontology can be found via the link below. The information includes a brief description of each release. A full description of each release can be found following the links on the Past Releases page.

xref:past_releases.adoc[Information on past releases can be found here.]
****

[.tile]
.Working Group Documents
****
This section contains minutes and reports of the Working Group activities and meetings listed by interest/ category.

xref:wg_corrections@EPO::index.adoc[Click here to read the working group documents]
****

[.tile]
.model2owl Documentation (to be hidden until content ready)
****
The model2owl Project consists of a set of tools for transforming a UML v2.5 model from its XMI v2.5.1 serialisation into a formal ontology.

//xref:xxx@EPO::model2owl.adoc[update when ready]
Updated documents coming soon.
****

--