= eProcurement Working Group Meetings

[.tile-container]
--

[.tile]
.ePO Working Group Meetings Cumulative Reports
****
The cumulative annual reports are a collation of minutes from all the ePO related meetings in a year. Reports from the years 2019 to 2023 are currently available.

xref:cumulative.adoc[Click here to access the cumulative reports]

****

[.tile]
.ePO Reports from the Working Group General Meetings
****
These reports contain the minutes from the general meetings, and outline project progress, changes implements since the last meeting, and future development plans for the next period.

xref:general.adoc[Click here to access the annual reports]
****


[.tile]
.ePO Working Group Meeting Reports: eCatalogue
****
This section contains the minutes eCatalogue from January 2022 onwards.

xref:eCatalogueMeetings.adoc[Click here to access the eCatalogue  reports]
****

[.tile]
.ePO Working Group Meetings Cumulative Reports: eFulfillment
****
This section contains the minutes eFulfillment from August 2022 onwards.

xref:eFulfilmentMeetings.adoc[Click here to access the eFulfillment  reports]
****

[.tile]
.ePO Working Group Meetings Cumulative Reports: eOrdering
****
This section contains the minutes eOrdering from July 2022 onwards.

xref:eOrderingMeetings.adoc[Click here to access the eFulfillment  reports]
****
--