:doctitle: eProcurement Ontology Documentation
:page-code: epo-v4.1.0-prod-001
:page-name: index
:docdate: March 2024


The eProcurement Ontology (ePO) defines and develops the semantic ontology related to EU public procurement. It creates and maintains the ontology according to EU regulations and directives.

The following topics are included in this version of the eProcurement Ontology documentation:


== General Documentation

* xref:business.adoc[Business Overview] +
Business Overview of this release
* xref:conceptual.adoc[Conceptual Models] +
The release specific conceptual Model(s)
* xref:glossaries.adoc[Glossaries] +
The release specific glossaries
* xref:release-notes.adoc[Release Notes] +
The release notes as on GitHub


== Reference Documentation
* xref:epo-home::references.adoc[Reference Documentation] +
Useful reference documents in the development of the ePO
* xref:epo-home::history.adoc[History and Planned Developments] +
Milestones in the project and future development plans
* xref:epo-home::versioning.adoc[ePO Versioning Rules] +
An overview of the versioning rules for releases

== Working Group Documents
* xref:epo-wgm::wider.adoc[Quarterly Meetings] +
Minutes, Presentations etc from the quarterly Working Group Meetings
* xref:epo-wgm::cumulative.adoc[Cumulative Reports (by year)] +
All weekly meetings minutes collated into yearly documents
* xref:epo-wgm::indiv.adoc[Individual Meeting Reports] +
All the weekly meeting minutes and documents saved individually
