== Mapping CM Classes

=== Mapping of the classes in the conceptual data model for the three use cases selected:  
|============================================================
|*Label*|*URI*
|Address|_http://www.w3.org/ns/locn#Address_
|Agent|_http://xmlns.com/foaf/spec/#term_Agent_
|Award Criterion| _\http://data.europa.eu/eproc/ontology#AwardCriterion_

Considering to reuse:

_\http://data.europa.eu/m8g/Criterion_

_http://purl.org/procurement/public-contracts#AwardCriteriaCombination_

_http://contsem.unizar.es/def/sector-publico/pproc#TenderRequirements_

|Buyer|_\http://www.omg.org/spec/EDMC-FIBO/FND/ProductsAndServices/ProductsAndServices/Buyer_

Alternative to reuse:

_\http://data.europa.eu/m8g/PublicOrganisation_

|Call For Tender|_\http://data.europa.eu/eproc/ontology#CallForTender_
|Classification|_\http://data.europa.eu/eproc/ontology#Classification_

Alternative to reuse:

_\http://www.eurocris.org/ontologies/cerif/1.3#Classification_

|Concept|_http://www.w3.org/2004/02/skos/core#Concept_
|Contract|_\http://www.omg.org/spec/EDMC-FIBO/FND/Agreements/Contracts/Contract_

Alternative to reuse:

_http://purl.org/procurement/public-contracts#Contract_

|Contract Award Notice|_http://contsem.unizar.es/def/sector-publico/pproc#ContractAwardNotice_
|Contracting Authority|_\http://data.europa.eu/eproc/ontology#ContractingAuthority_
|Country|_\http://data.europa.eu/eproc/ontology#Country_

Alternative to reuse:

_http://d-nb.info/standards/elementset/gnd#Country_

_\http://rdf.geospecies.org/ont/geospecies#Country_

|Currency|_\http://data.europa.eu/eproc/ontology#Currency_

Alternative to reuse:

_https://w3id.org/saref#Currency_

_\http://def.seegrid.csiro.au/isotc211/iso19103/2005/basic#Currency_

|Document|_\http://data.europa.eu/eproc/ontology#Document_

Alternative to reuse:

_http://www.omg.org/spec/EDMC-FIBO/FND/Arrangements/Documents/Document_

|Economic Operator|_\http://data.europa.eu/eproc/ontology#EconomicOperator_

Alternative to reuse:

_http://www.w3.org/ns/org#Organization_

|Evidence|_\http://data.europa.eu/m8g/Evidence_
|Exclusion Criterion|_\http://data.europa.eu/eproc/ontology#ExclusionCriterion_

Alternative to reuse:

_http://semanticscience.org/resource/SIO_000143_

_http://purl.obolibrary.org/obo/OBI_0500028_

|Invoice|_http://schema.org/Invoice_

Alternative to reuse:

_http://purl.org/cerif/frapo/Invoice_

|Location|_http://purl.org/dc/terms/Location_
|Monetary Value|_http://schema.org/MonetaryAmount_
|Organisation|_https://www.w3.org/TR/vocab-org/#class-organization_

Alternative to reuse:

_http://standard.open-contracting.org/latest/en/schema/reference/#organization_

|Other Contracting Entity|_\http://data.europa.eu/eproc/ontology#OtherContractingEntities_
|Payment|_\http://www.omg.org/spec/EDMC-FIBO/FND/ProductsAndServices/PaymentsAndSchedules/Payment_

Alternative to reuse:

_http://purl.org/cerif/frapo/Payment_

_\http://reference.data.gov.uk/def/payment#Payment_

|Call For Tender|_\http://data.europa.eu/eproc/ontology#CallForTender_

Considering to reuse:

_\http://data.europa.eu/m8g/FormalFramework_

|Procurement Criterion|_\http://data.europa.eu/m8g/Criterion_
|Procuring Entity|_http://standard.open-contracting.org/latest/en/schema/reference/#procuringEntity_
|Product Or Service Or Work|_\http://data.europa.eu/eproc/ontology#ProductOrServiceOrWork_

Alternative to reuse:

_http://purl.org/goodrelations/v1#ProductOrService_

_\http://data.europa.eu/m8g/PublicService_

|Public Undertaking|_\http://data.europa.eu/eproc/ontology#PublicUndertaking_
|Selection Criterion|_\http://data.europa.eu/eproc/ontology#SelectionCriterion_

Considering to reuse:

_\http://data.europa.eu/m8g/Criterion_

_http://contsem.unizar.es/def/sector-publico/pproc#TenderersRequirements_

|Specification|_http://semanticscience.org/resource/SIO_000090_
|Tender|_\http://data.europa.eu/eproc/ontology#Tender_

Alternative to reuse:

_\http://standard.open-contracting.org/latest/en/schema/definitions/Tender_

_\http://purl.org/procurement/public-contracts#Tender_

|============================================================

=== Submit an issue:  
To propose a new mapping for one of the class or to create any issue related to the mapping of the classes, please link:https://github.com/eprocurementontology/eprocurementontology/labels/Mapping%20CM%20-%20Classes[click here] and then click on "New issue".
For a new mapping, **adapt** the first column of the table proposed to follow the class template below:    

|============================================================
|*Element*|*Description*
|Label|A short title of the class, e.g. “Contract”
|URI|A string of characters used to identify a resource.|  
|============================================================

Use the second column of the template as guidance to propose a URI.