:doctitle: Guide to the ePO Modules
:doccode: epo-modguide-menu
:author: AD
:docdate: June 2024

== Introduction

== Why a Modular Approach

The Modularization of the Ontology offers three advantages as opposed to just having one Ontology file:

* Better Maintenance
* Reusability
** Better Management


==== 7/1/21 Topic of discussion: Usage of modules in the ePO ontology

Currently, all the diagrams are translated to a general owl file. In the case of BDTI, they produced a little piece with the data for its specific context.

The WG discussed to have small ontologies for each of the procurement phases. For example, to have a module for the eOrder with its classes and properties. The common classes could be in another package.

The WG indicated that using modules would allow reducing the complexity of the Ontology.

Everis raised the issue of how Enterprise Architect manages the reuse of classes from other packages. It creates a copy of the class, and any change created for classes reused is only applied to the specific UML diagram where it is used.

==== 14/12/2021 Argumentation on whether we should split ePO into different modules or keep all inside one big model.

If we add all modules inside ePO module, maintenance will be a mess in the future.
An idea is not to split everything per process, but per a domain.
Further discuss with domain experts on how to structure the module splitting.

== FAQ

===== Q: Is there a single file that contains all owl:imports needed to compose the full ePO?

No there is not. It depends on how someone plans to use the Ontology. For example, if someone wants to use the Ontology for querying information on eForms, they should use the eNotice module.

== ePO core

=== Description
ePO core is the main module of ePO ontology containing the fundamental parts of ePO. All the other ePO modules import the core module in order to use its concepts.

=== Imports
The imports of the core module are listed below:

  owl:imports cccev:,
        dcterms:,
        vann:,
        <http://www.w3.org/2004/02/skos/core>,
        <http://www.w3.org/2006/time>,
        <http://www.w3.org/ns/adms>,
        <http://www.w3.org/ns/locn>,
        org:,
        <http://www.w3.org/ns/person>,
        foaf: ;

== eCatalogue

== eOrdering

== eFulfilment

== eContract

== eAccess

== eSubmission

== eNotice

The eNotice module contains classes related to eNotices. It is structured in three packages: notice core, eForms standardisation, and standard Forms standardisation. The standardisation of the notices was done taking into account the notice types: planning, competition, direct award prenotification, result, contract modification and completion. This is the so-called “phase organisation of the notices”.

