:imagesdir: images
:downloaddir: download
:xrefstyle: short

:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:


= Ontology workgroup note-taking practice proposal

:toc:
:toc-placement: preamble
:toclevels: 1
:showtitle:

toc::[]

This document proposes a methodology on how to capture in a structured manner the discussions in of the expert working group.


== Requirements
This section captures the set of requirements for documenting the workgroup sessions.

* The workgroup meeting discussions need to be recorded so that on a latter occasion the reader know what were the topics addressed and teh decision on each of the topics.
* The workgroup decisions must be accessible on a public space, preferably next to the model.
* The notes should, where possible, contain visual representation or diagrams for better conveying the intended meaning.
* to be continued ...

== Session setup

*Moderator*

Each workgroup session should be conducted by a _moderator_, who is responsible to bing a meeting agenda or a general session theme, to direct the discussion flow, and optionally to moderate the turn-taking among participants.

The final goals and main responsibilities of the model editor are:

* ensure the discussions are efficient and concise so that the decisions and agreement can be reached in minimal amount of time.
* frame the discussions so well-defined issues are discussed one at a time.
* prepare the meeting agenda with a list of topics to address or a general session discussion theme.

*Model editor*

The session has at its center a view (or screen) of the model at work shared by the _model editor_. All the participants see the model view and discuss a given issue, its representation in the model or information from reference materials that need to be considered. The _model editor_ shows on the screen teh discussed model parts and if needed performs the necessary model editing actions to reflect what participants are discussing.

The final goals and main responsibilities of the model editor are:

* ensure teh model part under revision is consistent with the decision of the group
* ensure that the editing is complete (online or offline by the next session). If the editing is incomplete, the editor will either ask questions or require time to complete the model part editing, or take note of what shall be done after the session.
* implement all the previous session tasks before the next session (provided that the tasks were well specified and did not require domain expert validation)
* ask competency questions to the working group in order to elicit modeling aspects and implement them on the spot or record implementation tasks.

*Session secretary*

The session discussion is documented by the _session secretary_, who is responsible mainly of taking structured notes on the discussed issues and the decisions taken by the group. The taken notes must capture the discussed problems, the possible alternative solutions to it and the rationale why a solution is preferred.

The final goals and main responsibilities of the session secretary are:

* be clear what issue is discussed (most of the time). If teh discussion is out of the scope of the issue, then the course is gently turned back in.
* document as clearly as possible (in a structured manner) the basic aspects of each discussed issue. The preferred decision structure shall be compatible with _model anamnesis_ approach described in Section <<_model_anamnesis>>. If the documentation is incomplete, then the additional questions are asked in order to register a complete picture of the issue.
* record competency questions for each issue discussed that characterise on element of a part of the model.
* records model editing tasks that shall be executed after the session is complete and before the next session. This means that the tasks are not complex and are either model agnostic or very well specified so that no presence of no domain expert is necessary.
* publish the session notes at the end of each session together with the model change-log.

*Domain experts*

The _domain expert_ participants are discussing the issue proposed by the moderator. They provide insights and answer questions from the model editor, secretary and the moderator.

== Note-taking

The session note-taking shall be done preferably in a persistent collaborative environment. This means that solutions that allow simultaneous multi-user editing on the same document shall be preferred. All workgroup participants shall have access to the document or at minimum the session moderator, secretary and model editor.

Possible technical choices:

* Word and Excel files in Sharepoint/MsTeams
* Google Documents/Sheets

== Model anamnesis

The approach of recording a modelling and design decisions recommended here is based on [Plataniotis et.al. 2012] titled "EA Anamnesis: Towards an approach for EnterpriseArchitecture rationalization".
"Anamnesis", an ancient Greek word, is a term used in medicine, philosophy and other sciences and denotes reminiscence and repair of forgetfulness.

The "model anamnesis" approach proposes a specialised template that captures a model decision that is taken, in terms of decision attributes. The template form is presented in the table below.

[cols="3,7"]
|===
|Decision attribute |Description

|*Title*
|_A small but informative description of the EA decision that was taken._

|*Issue* _(the problem)_
|_This ﬁeld addresses the issue that the Enterprise Architect had to solve with this decision. It is a short description of the issue and not an argumentation for thedecision._

|*Alternative choices* _(the possible solutions)_
|_This ﬁeld describes the alternative choices that were considered for the same EA issue. An architect can use alternatives to describe the alternative options for addressing the EA issue._

|*Rationale*
|_The reason that leads the architect to choose the speciﬁc decision among the alternatives. A rationale answers the “why” question for each decision. The information of this ﬁeld should provide some added value to the overall decision of the information._

|*Notes*
|_Here are recorded general and additional information that help tehr eader to better understand the issue_
|===

== Versioning system

A versioning system shall be used consistently for storing the model and tracking its evolution over time. In a similar manner the work group notes and session documentation shall be stored and tracked over time.

For the Enterprise Architect Models, there are several alternatives available. One of them, native to the Enterprise Architect is establishment of a model repository available in the Corporate, Unified and Ultimate versions of the software. A more widely known and open approach is using the Git versioning system.

For EPO model the GitHub solution is chosen. A similar approach or one available in the GitHub ecosystem shall be adopted for the model documentation and the work group meetings. The GitHub wiki, GitHub pages with Sphinx or AsciiDoc are only a few approaches that can be adopted.

It is a good practice to edit the model in session specific branches. This however not be always possible or convenient. The important part is to be able to identify the model version before the beginning of the workgroup session and the model version after its completion.

== Publishing

The model evolution over time shall be published so that the wider public has access to a specific (tagged) version of the model, a development branch or the latest stable version of the model.

When publishing the following aspects shall be available:
* the session notes covering the issues discussed and the associated decisions
* the (reference to) model version before the session
* the (reference to) model version after the session
* the diff report between the initial and final models, which is automatically generated and lists the atomic changes in the model.

Each well-defined set of model changes that can also be properly delimited and motivated must be documented using the model anamnesis approach described in Section <<_model_anamnesis>>. A well-defined set of changes can be framed by:

* a workgroup session covering a list of documented issues
* an offline modelling session executing a set of tasks or an implementation of a well-defined modelling target.

== Proposed workflow & tools

=== Note-taking

A lucrative Google Docs or Sharepoint shared folder where date-tagged documents are added.

Google Docs is preferred because it is collaborative concomitant multi-editor application with available add-ons that are instrumental to publishing in Markdown or AsciiDoc format on GitHub.

=== Generating the AsciiDoc/Markdown session notes

In Google Doc use the add-ons "Articul8" or "AsciiDoc Processor" to export the preferred output format.

=== Generating the model-diff report

Unfortunately there are not many tools that can generate a comprehensive change-notes report between two versions of a model. One such tool is called LemonTree.

It has advantages such as: allowing to use Git versioning natively from Enterprise Architect, comparing versions of two models in ain interactive manner, merging and resolving conflicts between versions of a model.

The downside is that no human-readable diff-report can be generated, which means that  the change-log is available only as a diffing session that can be seen using LemonTree software.

Using LemonTree shall be generated an interactive session that contains the compared EA models. This method shall be used until a replacement method to generate the human-readable model diff-report is found.

=== Committing to GitHub

The model changes shall be committed soon after the session is complete. The session decision notes and the diff report must follow the model commit.

=== Publishing the notes as GitHub pages

Once the notes are committed to GitHub they shall be published for the broader public. This shall be done by setting up GitHub Action automations that execute Antora playbook and produce the GitHub pages.