:doctitle: Other Reference Documents
:doccode: epo-main-prod-007
:author: AD
:docdate: June 2024



== *20 May 2020: eProcurement UML conceptual model conventions and transformation into a formal OWL ontology*
InfEurope delivered two documents commissioned by the EU Publications Office. The first one on the xref:REFumlconv2020.adoc[eProcurement ontology UML conceptual model conventions], describing how to represent ePO using the UML , and the second one explaining xref:REFuml2owl_2020.adoc[how to transform such UML documents into OWL Ontologies].


== *17 April 2020: eProcurement Ontology Architecture and Formalisation Specifications*
InfEurope delivered a report commissioned by the EU Publications Office on the xref:REFePO_Arch_Design.adoc[eProcurement ontology architecture and formalisation specifications] on the 17 April 2020, describing the ePO architecture at a technical level, including technologies, process and methodology, and conceptual models. The report can be accessed xref:REFePO_Arch_Design.adoc[here]

== *3 August 2017: Specification of the Project Process and Methodology, and Project Charter Proposal*
On the 3 August 2017, PWC EU Services delivered two documents commissioned by the Publications Office of the EU, and funded by the ISA^2^ Project, the first draft of document, xref:REFspecification.adoc[Specification of the Process and Methodology to develop the eProcurement Ontology], and version 1.0 of a second report, the D02.02 xref:REFcharter.adoc[Project Charter Proposal], which describes the project, listing its scope, stakeholders, success criteria, deliverables, costs and other aspects essential to, or covered by, the project.

The Specification and Methodology can be found xref:REFspecification.adoc[here].
The Project Charter Proposal can be accessed xref:REFcharter.adoc[here].

== *20 September 2016: First Support for an eProcurement Ontology*
On the 20 September 2016, PWC EU Services was contracted, by the publications Office of the EU, to provide version 1.00 of a report, the D04.07 Report on policy support for e-Procurement, known as the xref:REFlandscaping.adoc[Landscaping Document], for the ISA Project, the initial funder of the eProcurement Ontology Project.

The document sets the context for an eProcurement Ontology, proposes a solution, and addresses topics such as process, methodology, technology, and audience, and then concludes, and proposes the next steps in the project. The xref:REFlandscaping.adoc[full report] can be accessed xref:REFlandscaping.adoc[here].

== *08 December 2014: Methodology and tools for Metadata Governance and Management for EU Institutions and Member States*

The document can be accessed xref:REFmetgovman.adoc[here].

include::partial$feedback.adoc[]


