== *ePO - eProcurement Ontology 1.0.0*

The D02.01 Specification of the process and methodology can be downloaded from link:https://joinup.ec.europa.eu/asset/eprocurementontology/document/d0201-specification-process-and-methodology-develop-eprocurement[here].
The D02.02 Project Charter proposal can be read link:https://joinup.ec.europa.eu/asset/eprocurementontology/document/d0202-project-charter-proposal-v100[here].

The landscaping report on policy support for e-Procurement is available link:https://joinup.ec.europa.eu/asset/eprocurementontology/document/report-policy-support-e-procurement[here].

The OWL file created from the current data model is available link:https://github.com/OP-TED/ePO/blob/v1.0.0/v1.0.0/03_Implementation/ttl/eproc_v0.6.owl[here].

== *Release Notes*

=== Version 1.0.0

* Defines of three Use Cases:
** Use Case 1: "Data Journalism"
** Use Case 2: "Automated matchmaking of procured services and products with businesses"
** Use case 3: "Verifying VAT payments on intra-community service provision"
* Identifies Information Requirements in alignment with the Use Cases
* Defines a _Conceptual Data Model_ 
* Maps the Conceptual Data Model entities to OWL
* Implements the Conceptual Data Model in OWL 
* Release year: 2017