:doctitle: eProcurement Ontology
:doccode: epo-v4.0.0-rc.1-prod-002
:author: Andreea Pasare
:authoremail:
:docdate: July 2023

== *Release notes 4.0.0-rc.1*

The 4.0.0-rc.1 and its corresponding technical files can be found link:https://github.com/OP-TED/ePO/tree/v4.0.0-rc.1[here].

RDF representation of the eProcurement ontology can be downloaded link:https://github.com/OP-TED/ePO/tree/v4.0.0-rc.1/implementation/ePO[here].

RDF representation of the eCatalogue module can be downloaded link:https://github.com/OP-TED/ePO/tree/v4.0.0-rc.1/implementation/eCatalogue[here].

RDF representation of the eOrdering module can be downloaded link:https://github.com/OP-TED/ePO/tree/v4.0.0-rc.1/implementation/eOrdering[here].

RDF representation of the eFulfilment module can be downloaded link:https://github.com/OP-TED/ePO/tree/v4.0.0-rc.1/implementation/eNotice[here].

RDF representation of the eContract module can be downloaded link:https://github.com/OP-TED/ePO/tree/v4.0.0-rc.1/implementation/eNotice[here].

RDF representation of the eNotice module can be downloaded link:https://github.com/OP-TED/ePO/tree/v4.0.0-rc.1/implementation/eNotice[here].

== Release notes

|===
|*Metadata*|*Value*

|Reference ePO version|3.1.0
|Target ePO version|4.0.0-rc.1
|Authors|Andreea Pasăre, Eugeniu Costetchi
|Date|2023-07-19
|===

* Modeling Procedure in the context of a Mini-Competition:
** Award in the context of a Framework Agreement
** Award in the context of a Dynamic Purchasing System

* Standard form mapping requirements:
** Communication means
** Procurement Criteria Summary
** Notice relations harmonisation

* eForm mapping requirements:
** Ensure coverage of all BTs from the new eForm Annex
** Implemented new eForm business terms
** Revision of all monetary values

* New module development: eFulfilment, eContract

* Post-Award modules alignment (eCatalogue, eOrdering, eFulfilment):
** Creation of information hubs to allow data to be provided either at document or line level if not a combination of the two
** Modelling of different charges allowing for the different requirements across the different phases
** Deliverable becomes a subclass of the Item
** PostAward Objects become Documents

include::partial$feedback.adoc[]