= *eInvoicing – Ontology Requirements Specification Document (ORSD)*

== *Resources*

. eInvoicing semantic data model (SR EN 16931)
. https://docs.peppol.eu/poacc/billing/3.0/bis/[https://docs.peppol.eu/poacc/billing/3.0/bis/]

== *eInvoicing*   +
In the procurement domain, eInvoicing (electronic invoicing) refers to the digital exchange of invoice documents between a Buyer and a Seller. Unlike traditional paper invoices, eInvoices are generated, transmitted, and received in a structured digital format (typically using XML), thus enabling faster and more accurate processing, reducing errors and enhancing compliance with tax regulations.   +
eInvoicing improves efficiency, enables real-time tracking, and supports better financial management by streamlining the entire invoicing workflow.  In the context of eProcurement Ontology (ePO), eInvoicing plays a crucial role in understanding the actual public spending. Modelling the concepts from the eInvoicing in the eProcurement Ontology will enable the creation of data sets containing invoicing information. Such data sets are foreseen in solutions like the https://single-market-economy.ec.europa.eu/single-market/public-procurement/digital-procurement/public-procurement-data-space-ppds_en[Public Procurement Data Space] (PPDS).

=== *Roles involved*

* Buyer
* Seller
* Payee (if it is different than the Seller)
* Seller Tax representative
The model does not explicitly show who the service provider is, nor are any checks made on who the service provider is.

=== *Activity description*

. The Seller generates an invoice and the additional supporting documents.
. The Seller sends the invoice to the Buyer.
. The Buyer receives and processes the invoice.
. The Buyer pays the Seller/Payee the amount of the invoice before the due date.
*Other administrative flows to be covered (for example penalties, cancelled invoice etc.)

=== *Use case*
|===
|*Use case* |*Description* |*Actors* |*Flow*

|1. Generating the Invoice |The Seller generates an invoice with the amount the Buyer needs to pay for the received goods, services or supplies. |Seller |The Seller generates an invoice.
|2. Sending the Invoice |The Invoice sender sends the invoice to the Buyer to be reviewed and processed by the Buyer. |Seller |The Seller sends the invoice to the Buyer.
|3. Receiving and processing the Invoice |The Buyer receives and processes the Invoice so he can pay for the received goods, services or supplies. |Buyer |The Buyer receives and processes the Invoice.
|4. Invoice payment |The Buyer pays the Seller the amount of the invoice before the due date |Buyer |The Buyer pays the Seller the amount of the Invoice.
|===


*User Stories*
|===
|*Code* |*Role*  |*User Story*

|INV-1 |Buyer |As a Buyer, I want to know the Seller's identification information at the invoice (document) level.
|INV-2 |Buyer |As a Buyer, I want to know the Payee identification information at invoice (document) level, if different from the Seller.
|INV-3 |Buyer |As a Buyer I want to know the information about payment at invoice (document) level.
|INV-4 |Seller |As a Seller, I want to know the Buyer's financial account information.
|INV-5 |Buyer |As a Buyer I want to know the information to trace back to the related order at the invoice (document) level.
|INV-6 |Buyer |As a Buyer I want to know the information to trace back to the related order line at the invoice line level.
|INV-7 |Buyer |As a Buyer I want to know the information to trace back to the related contract from the invoice (document) level.
|INV-8 |Buyer |As a Buyer I want to know the information to trace back to the related despatch advice from the invoice (document) level.
|INV-9 |Buyer |As a Buyer I want to know the information to trace back to the related receipt advice from the invoice (document) level.
|===

=== *Natural Language Statements*


. An invoice has an unique identifier.
. An invoice has a date of issuance.
. An invoice can have a payment due date.
. An invoice must have a currency of all the amounts (except for the total VAT amount in accounting currency).
. An invoice can refer to the procurement project.
. An invoice can refer to the contract.
. An invoice can refer to an order.
. An invoice can refer to a despatch advice.
. An invoice can refer to a receipt advice.
. An invoice can refer to a lot.
. An invoice can have a textual note.
. An invoice can have payment terms.
. An invoice can refer to previous invoices.
. An invoice has to specify information about the Seller.
. An invoice has to specify information about the address of the Seller.
. An invoice can specify the contact point information of the Seller.
. An invoice has to specify information about the Buyer.
. An invoice has to specify information about the address of the Buyer.
. An invoice can specify the contact point information of the Buyer.
. An invoice can specify information about the Payee, if different than the Seller.
. An invoice can specify information about the Seller's tax representative.
. An invoice can specify information about where and when the goods and services invoiced are delivered.
. An invoice can specify information about it's delivery period.
. An invoice can specify information about the address to which goods and services invoiced were or are delivered.
. An invoice can specify the payment instructions.
. An invoice can specify the credit transfer payments.
. An invoice can specify information about a card used for payment contemporaneous with invoice issuance.
. An invoice can specify a direct debit.
. An invoice can specify information about allowances applicable to the Invoice as a whole.
. An invoice can specify information about charges and taxes other than VAT, applicable to the invoice as a whole.
. An invoice has to specify the monetary totals for the invoice.
. An invoice has to specify information about VAT breakdown by different categories, rates and exemption reasons.
. An invoice may refer to one or many additional supporting documents.
. An invoice has to refer to one or many invoice lines.
. An invoice line may specify information about it's delivery period.
. An invoice line may specify information about allowances applicable to the Invoice as a whole.
. An invoice line may specify information about charges and taxes other than VAT, applicable to the invoice as a whole.
. An invoice line has to specify information about the price applied for the goods and services invoiced on the invoice line.
. An invoice line has to specify information about the VAT applicable for the goods and services invoiced on the invoice line.
. An invoice line has to specify information about the goods and services invoiced on the invoice line.
. An invoice line may provide information about properties of the goods and services invoiced.


