:doctitle: User Stories and Natural Language Statements
:doccode: epo-main-prod-039
:author: NPJ
:authoremail: nicole-anne.paterson-jones@ext.ec.europa.eu
:docdate: February 2024

== Introduction

When expanding the eProcurement Ontology with new modules, the https://lot.linkeddata.es/[Linked Open Terms or "LOT"] methodology is used. 

According to LOT, the first step in developing an ontology is to collect the requirements the ontology should fulfill. The outcome is then an Ontology Requirements Specification which is made up of Use Cases, User Stories, and Natural Language Statements:
 
* Use cases describe situations that need to be covered by the ontology. 
* User Stories are created from use cases and are structured around three main questions: 
** Who is the beneficiary of an action (who benefits from it)? 
** What is the need? 
** What is the benefit? 

Natural Language Statements can be affirmative or negative statements where each statement defines a requirement that must be included in the ontology. 

include::stories_eAccess.adoc[]

include::stories_eSubmission.adoc[]