== *Reference Documents*

=== *20 September 2016: First Support for an eProcurement Ontology*
On the 20 September 2016, PWC EU Services issued version 1.00 of a report, the D04.07 Report on policy support for e-Procurement (e-Procurement ontology), known as the link:{attachmentsdir}/Landscaping_document.docx[Landscaping Document], for the ISA Project, the initial funder of the eProcurement Ontology Project.

The document sets the context for an eProcurement Ontology, proposes a solution, and addresses topics such as process, methodology, technology, audience, concludes, and proposes the next steps in the project.The link:{attachmentsdir}/Landscaping_document.docx[full report] can be accessed link:{attachmentsdir}/Landscaping_document.docx[here].

'''
=== *3 August 2017: Specification of the Project Process and Methodology, and Project Charter Proposal*
On the 3 August 2017, PWC EU Services issued the first draft of document, link:{attachmentsdir}/d02.01_specification_of_the_process_and_methodology_v1.00.pdf[Specification of the Process and Methodology to develop the eProcurement Ontology ], and version 1.0 of a second report, the D02.02 link:{attachmentsdir}/d02.02_project_charter_proposal_v1.00_0.pdf[Project charter proposal], describing the project, listing its scope, stakeholders, success criteria, deliverables, costs and other aspects essential to or covered by the project. 

The Specification and Methodology can be found link:{attachmentsdir}/d02.01_specification_of_the_process_and_methodology_v1.00.pdf[here].
The Project Charter Proposal can be accessed link:{attachmentsdir}/d02.02_project_charter_proposal_v1.00_0.pdf[here].

'''
=== *17 April 2020: eProcurement Ontology Architecture and Formalisation Specifications*
InfEurope completed a report for the EU Publications Office on the link:https://github.com/meaningfy-ws/model2owl/blob/master/doc/ontology-architecture/ontology-architecture.pdf[eProcurement ontology architecture and formalisation specifications] on the 17 April 2020, which describes the architecture at a technical level, including technologies, process and methodology, and conceptual models. The report can be accessed link:https://github.com/meaningfy-ws/model2owl/blob/master/doc/ontology-architecture/ontology-architecture.pdf[here]

'''
=== *17 April 2020: The eProcurement UML Conceptual Model Conventions*

link:https://github.com/meaningfy-ws/model2owl/blob/master/doc/uml-conventions/uml-conventions.pdf[The UML Model Conventions]

'''
=== *20 May 2020: Transformation of the eProcurement UML Model into a Formal OWL Ontology*

link:https://github.com/meaningfy-ws/model2owl/blob/master/doc/uml2owl-transformation/uml2owl-transformation.pdf[The UML to OWL Transformation Rules]


include::partial$feedback.adoc[]