== Meeting 11/11/2019

Participants: Vibeke Engesaeth, Cécile Guasch, Thor Moeller, Natalie Muric, Giampaolo Sellitto, Juan Carlos Segura, Jalini Srisgantharajah and Enric Staromiejski.

The meeting of 11th November was focused on the mapping of the PINs in the Planning phase.

Everis explained to the WG the situation detected during the mapping performed. During the mapping, Everis detected that the new regulation says that the “Procedure” in some cases is optional and mandatory, and therefore this creates confusion since in the Planning phase the Planned Procurement Part should be used instead the Procedure. The same situation happens with the Lot which force us to make the mapping through Lot class.

According to the situation explained by Everis, the WG decided to work in some BTs in order to find a solution. The WG took the BG-2 Purpose. The definition says: “the Information about the purpose. This information must be given for the whole procurement procedure and, if they exist, also per lot. In case of a prior information notice used only for in¬formation, this information may differ per part of the notice that may later become a lot or a self-standing procedure”. The WG said that this definition should also make reference to the Planned Procurement Part and not only to the Procedure and lot.