== Meeting: 12/11/2019

Participants: Paloma Arillo Aranda, Cécile Guasch, Thor Moller, Natalie Muric, Giampaolo Sellitto, Juan Carlos Segura and Enric Staromiejski.

The meeting of the 12th November was focused on two topics: Mapping of the Planning stage and IFLA presentation related to the versioning.

Everis started the meeting with the mappings performed internally. Everis explained that those cases where the Lot and Procedure are needed for the mapping, they have been indicated in the mappings file. Enric also explained that he talked with Marc Christopher Schmidt from DG GROW regarding the use of Procedure in the Planning Stage. As a conclusion of the call, Marc Christopher proposed to create an issue.  Everis agreed with the WG,  proposed to create an issue in the eForms GitHub platform in order to clarify the situation detected. The WG agreed that it is also needed to understand whether the purpose foresee, or not, planned procurement as well as procurement and lots.

After the mapping status explanation, Enric continued the meeting with the IFLA presentation related to the versioning. Enric indicated that regarding the versioning, LEX has 2 types of versions: (1) Multi-version and (2) Single version. However, Enric indicated that in ePO the idea is to have only 1 version, a single version which means a new distinct object per version. This new object contains classes explicitly designed to indicate which parts of the documents have change, how, the reason, etc.

Enric continued the presentation explaining the kind of versioning used in LEX and the proposal for ePO:

* LEX
**	Current: in-force version
**	Self: this version
**	Next: next version
**	Previous: previous version
**	First: Original version
* ePO
**	Current: in-force
**	Previous

Enric proposed the following identification of the version in ePO:

*	CEN/BII (CEN TC440) versioning policy -> MajorVersionID.MinorVersionID.BugFixingID

After the versioning explanation, the meeting was focused on how to represent the attributes and properties in the ontology. This discussion came from the need of to have naming and design rules. Everis will work on the definition of the naming and design rules for ePO.