== Working Group meeting 08/10/2020

Participants: Paloma Arillo Aranda, Cécile Guasch, Natalie Muric, Roberto Reale, Helder Santos, Juan Carlos Segura, Giampaolo Sellitto, Jalini Srisgantharajah, and Enric Staromiejski

**Topic of discussion: Roles and Subroles**

The WG started the discussion with proposing some clarification examples from the discussion on the 6th of October. From the clarifications, The WG made a general question about how a business person could understand what is represented in the UML. The WG, as an example to understand this need, said that if we are doing a mapping we need to understand from the UML to what we are mapping. One possibility could be the addition of notes in the UML to explain what is represented in the diagram.

For example, the creation of a note in the eAward diagram to explain which roles are involved in the awarding process. This note could say that the award decision involves only 2 roles: 1. The buyer, the one that awards; 2. The winner, the one that is awarded. Moreover, everis indicated that in this note can be added a reference to a ppt with more details of the roles-taxonomy representation, for instance. The WG replied that the problem is that we will end with a lot of notes in different diagrams and what will happen when it is automatized.

The WG also asked how the reification is helping in the eAward diagram. The reply was that the function of the reification is to link one agent/role with a specific activity. The WG thought that the reification is not needed in the AwardDecision and the AwardDecision could be considered as the reification. Everis indicated that the reification is needed because of the existence of the Agent and there are no other ways to know who is the agent/role/contact point behind the award decision. The WG did not see the need to have the reification in the AwardDecision diagram. There could be different winners in the decision 1 or 10, there is no problem, and the Buyer does not have other or more activities in the award decision. Everis said that if there is no reification and you want to instantiate the agent that wins the lot, to do that you need to have multiple instances of the winner and to see which instance is connected to one agent. The reification solves the problem to instantiate a role multiple times.

The conclusion and decision were that the reification will not point anymore to the taxonomy, it will point to the classes. The WG worked in such a solution, instead to have the class "AwardInvolvement" linked to the "role-taxonomy", now such class is linked to the winner through the property "involvesWinner". The discussion came from the need that the award decision/award involvement only involves 2 roles, the buyer and the winner. The buyer is not connected to the AwardInvolvement because it belongs to the responsibility of the procedure.