== Please find below the minutes of the 20th October:

Participants: Ana Aido Cécile Guasch, Giorgia Lodi, Roberto Reale, Helder Santos, Juan Carlos Segura, Giampaolo Sellitto, and Enric Staromiejski.

**Topic of discussion: Review of the minutes from the 13th and 15th of October**

* In the minutes from the 15th of October, instead of pointing to the eap file, better to add a picture of the diagram;
* Typo in the second bullet,  "discussed" is missing;
* To add why the property relatesTo;
* To add a bullet point that we end the meeting with the discussion if the AwardDecsion is the reification class;

**Topic of discussion: eOrdering**

The WG continued working on the creation of the eOrdering diagram. The WG merged the Model were there was the eOrdering with the model where the work about roles and activites (subroles) is also being developed.

The EAP file can be found at link:https://github.com/OP-TED/ePO/blob/feature/frozen-2.0.2/implementation/test/roles-as-classes/ePO-CM-roles-as-classes.eap[ePO CM roles as classes]

In this EAP file the WG created a new diagram named 'eOrdering'. A png of this diagram is

link:https://github.com/OP-TED/ePO/blob/feature/frozen-2.0.2/implementation/test/roles-as-classes/img/eOrderingReification.jpg[eOrdering Reification]

In the above mentioned diagram it is possible to observe that WG was focused on the development of the eOrdering from the Roles perspective. Hence WG has added classes such as Deliveree, Deliverer, Originator, etc. When adding these classes the WG has reflected about the facts that:

* The information relative to which roles intervene in the eOrdering phase are normally specified as "Order Terms";
* At the stage of eOrdering, the roles do not seem to carry very much information, however we foresee that the actions and other properties related to the agents playing those roles will emerge when "fulfilling" the Order;
* This reflection has led the WG to identify that we may be in front of two different types of reifications:
** Reification to specify "information", "terms" or "conditions" anounced by the buyer related to the ordering; and
** Reification to describe "situations" related to the fulfilling of the order;
* In the first case, some members of the WG proposed to name the reification "RolesAssignment", since in their opinion this is merely about to identify which roles play one specific (and only one) Agent, and nothing else. Other alternatives were suggested for the naming of this reification (Ordering, OrderingInformation, OrderingTerms even).
* The discussion ends at this point (16:30), and the WG proposes to go on discussing on the Roles in the context of eOrdering.


**Action Point:**

* To add the link to the eOrdering file in the minutes.
* To check what is happening with the class Lot. It is in grey.