== Working Group meeting 30/04/2020

Participants: Paloma Arillo Aranda, Vibeke Engesaeth, Cécile Guasch, Giorgia Lodi, Thor Møller, Natalie Muric, Roberto Reale, Helder Santos, Juan Carlos Segura, Giampaolo Sellitto, and Enric Staromiejski.

**Topic of Discussion:** Buyer Profile

During this meeting, the WG discussed whether the Buyer Profile was needed or if it could be replaced by another existing class. In the course of this discussion the following exchange of ideas were debate:

* According to the model, a Buyer has a Buyer Profile which is a "Website address where the buyer publishes information on its procurement procedures and general information.". According to this definition, the WG saw clearly that a Buyer Profile is a Channel. With that proposal, the Buyer which is a role and plays the role of an Agent and the Buyer uses the Buyer Profile, which is a Channel.
* The  WG proposed that there is no need to have a URL attribute for the Buyer Profile since the Channel already has a URL.
* The WG proposed to link the channel and the agent through the property "ownedBy". The WG was inspired by the Core Public Service Vocabulary. This property has to be understood as who is the responsible of the channel.

The WG after a long discussion agreed on the following decisions:

* Keep buyer profile which is a Channel.
* We use the buyer profile at the Notification time.
* After a discussion on the property "ownedBy" the WG decided to keep and added a definition to clarify what OwnedBy means.