== Please find below the minutes from 30th of January:

Participants: Paloma Arillo, Ana-Maria Babaligea, Cécile Guasch, Giorgia Lodi, Vibeke Engesaeth, Natalie Muric, Roberto Reale, Giampaolo Sellito, Juan Carlos Segura, Jalini Srisgantharajah and Enric Staromiejski.

The approach of the meeting on the 30th January was focused on the continuation of the discussion of the everis’ proposal regarding the “Agent” class.

Everis and OP shared with the WG a copy of the old and new Buyer version as well as a view of the agent diagram that it is suggested to replace the organisation diagram, along with the organisation diagram. The WG used the occasion to discuss the email sent by Georgia regarding the usage of “Agent” and/or the “Organisation” classes and some doubts raised up after her analysis.

The WG proposes to have a base class that inherits from Agent which represent the legal status. This coul be a legal entity since att the end a legal entity can be an organization. However, in ePO we need to represent also a system and therefore it can not be considered a Legal entity.

The WG discussed what is a “ProcurementServiceProvider”. The WG said that a good example of it is an eSender and it can act on behalf of Buyer. This clarification raised up a discussion about the usage of “role” properties. The WG explained that we did not focus on processes during the development of the ontology and we did not use roles. Now the problem is what happens when a buyer is an agent. In order to solve this problem, everis proposed to use the property "isA" instead of to use "Role". Moreover, another proposed solution was to create a role class that could act as the role of the buyer, and therefore, there is no need to use the property role. The WG created a new diagram to reflect the different possible solutions proposed.

After the reflection, the WG decided to create the new class “Role” which is an abstract class. In addition, it was point out that an abstract class organisation role was needed between the different classes ie “buyer” and “agent” to allow an organisation in different cases to be either buyer or economic operator without having to have its information introduced twice and therefore leaving open the opportunity for error conflicting information.However, this approach is still under discussion.

The picture below shows an example created for the reflection analysis whether to create or not a role class:

image::30012020(1).jpg[Role class diagram]

And here the new diagram created for the discussion of the procurement roles:

image::30012020(2).jpg[Procurement roles diagram]

*Action Points:*

* @everis: Presentation in the F2F meeting about old discussions regarding “Buyer”.
* @everis: Attention to abstract classes role and agent need to paid when substantiating.

*Interesting links shared during the meeting:*

* http://ontologydesignpatterns.org/wiki/Submissions:AgentRole
* https://sparontologies.github.io/pro/current/pro.html