== Please find below the minutes from the 3rd November:

Participants: Paloma Arillo Aranda, Cécile Guasch, Giorgia Lodi, Natalie Muric, Roberto Reale, Juan Carlos Segura Fernández-Carnicero, and Enric Staromiejski.

**Topic of discussion: Review of the minutes from 27th and 29th October**

* Concerning the Ordering term, the WG indicated that the decision was not to have the Ordering term. Action for everis to include the final decision on the minutes.

**Topic of discussion: eOrdering**

Once reviewed the minutes of the last week, the WG continued with the discussions on the eOrdering model. Based on the minutes from the 27th and 29th of October, the following discussions took place:

* The WG saw that the properties from OrderingSituration to the different roles are not needed because the OrderingSituation which a ProcurementSituation already involves roles:

link:https://github.com/OP-TED/ePO/blob/feature/frozen-2.0.2/implementation/test/roles-as-classes/img/OrderingSituation%20and%20roles.JPG[Ordering Situation and Roles]

* The inclusion of the role and the agent in the generic reification class "ProcurementSituation" makes unnecessary the axioms that we have in versions 2.0.1 and 2.0.2 "epo:Agent epo:playsRole epo:Role and the inverse epo:Role epo:isPlayedBy epo:Agent". The inclusion of the epo:involvesRole in the reification, subclasses now the CPSV-AP property "cps-av:role" (we are reusing the cpsv-ap:Participation class and its attibute "role", which points to a "skos:Concept" (see the UML diagram for more details). Therefore, if we end up implementing the reifications as represented in the UML diagram above, the relation between roles and agents would have to be removed.
* The WG asked why we are inheriting Agent and ProcurementSituation from the CPSV and the conclusion was that we are inheriting Agent and ProcurementSituation from the cpsv:Agent and cpsv:Participation for two reasons/benefits: (1)for the benefits of alignment ontologies (e.g. SDG), (2) doing this alignment we also solve other problems like how the agent is being modeled through the reuse of the cpsv agent.

**Topic of discussion: Issues**

* Issue #255 (https://github.com/eprocurementontology/eprocurementontology/issues/255)
* Issue #256 (https://github.com/eprocurementontology/eprocurementontology/issues/256)