== Working Group meeting 01/12/2020

Participants: Paloma Arillo Aranda, Giorgia Lodi, Natalie Muric, Helder Santos, Juan Carlos Segura Fernández-Carnicero, Giampaolo Sellitto, and Enric Staromiejski.

**Topic of discussion: Review of the minutes from the 24th and 26th November 2020**

* We modified the minutes from the past 24th of November 2020 to reword some sentences that needed clarification.
* The axiom "_epo:CentralPurchasingBody epo:has epo:Buyer_ profile" was finally removed from the EAP file, since it had been indicated in the minutes but was not applied yet.
* A new axiom "_epo:Buyer epo:hasBuyerProfile epo:BuyerProfile_" has been created in v2.0.2, this way this version is harmonised to v2.0.1 (in the previous v2.0.2 version the subject was epo:Agent). In v2.0.1 the predicate is still "_epo:has_", since  we cannot change it due to the TED-RDF mapping (currently ongoing).
* The property "_usesBuyerProfile_", between "_epo:Agent_" and "_epo:BuyerProfile_" has been removed: it does not bring any semantics that can be correctly interpreted in eNotification.

**Topic of discussion: Issues**

The following issues were discussed, and many of them closed. Follow the links to get into the discussion and how it has been/is being solved:

* [Issue #253](https://github.com/eprocurementontology/eprocurementontology/issues/253)
* [Issue #254](https://github.com/eprocurementontology/eprocurementontology/issues/254)
* [Issue #258](https://github.com/eprocurementontology/eprocurementontology/issues/258)
* [Issue #250](https://github.com/eprocurementontology/eprocurementontology/issues/250)
* [Issue #249](https://github.com/eprocurementontology/eprocurementontology/issues/249)
* [Issue #251](https://github.com/eprocurementontology/eprocurementontology/issues/251)
* [Issue #268](https://github.com/eprocurementontology/eprocurementontology/issues/268)
* [Issue #248](https://github.com/eprocurementontology/eprocurementontology/issues/248)
* [Issue #269](https://github.com/eprocurementontology/eprocurementontology/issues/269)