== Please find below the minutes of the 25th of June:

Participants: Ana Aido, Paloma Arillo Aranda, Cécile Guasch, Giorgia Lodi, Thor Møller, Natalie Muric, Juan Carlos Segura Fernández-Carnicero, Giampaolo Sellitto, Jalini Srisgantharajah and Enric Staromiejski.

**Topic of discussion**: Roles and Subroles

The meeting was focused on the everis presentation on how to model the roles and subroles in the ontology. Everis created a presentation (link:{attachmentsdir}/presentations/Everis_Roles&Subroles.pptx[Roles and Subroles]) to gather different possibilities on how to model the roles and subroles. The Everis proposal is to create a reification that allows to link the roles and subroles with Lots. A reification is the ability to treat a Statement as a Resource , and hence to make assertions about that statement. A statement may be reified as many different resources, allowing different manifestations (“statings”) of that statement to be treated differently if required.

After the presentation of the everis solution, the WG said that the solution lacks the relationship between the Agent and the new reification class. Everis did not agree because in the end the class agent is a metaclass, and therefore a Role is at the end an agent.

Everis also presented an example in RDF to show how the roles and subroles model should be solved. The WG asked that according to the RDF presented, how the users will know that the Agent is uniquely identified by a role. The WG thoughts that the Agent needs to be linked to the reification. The WG also discussed whether the contact point should be linked or not to the role and agent.

The WG discussed the name of the reification class. The proposed name is "ProcedureRoleActivity". The WG says "ProcedureInvolvement".
WG by the moment to use the Cécile solution from last week.

Some other discussions were:

* It is needed to remove the link between role and contract point.
* The reification needs to link Agent, role, subrole, lot, and contact point.

*Conclusion:*

As the everis proposal is not enough clear and needs more discussion, the WG decided to create a temporary solution that is based in to create the subroles as properties that link the different roles to the Lot.
