== Working Group meeting 30/07/2020

**Participants 30th**: Ana Aido, Paloma Arillo Aranda, Cécile Guash, Giorgia Lodi, Thor Møller, Giampaolo Sellitto, Héctor Rico and Enric Staromiejski.

**Topics of Discussion**: CPB, Framework Agreement Technique, Pending Topics from the current TED forms mappings.

**Central Purchasing Body: (Issue 245 CPB can be responsibleOf procedure)**
For the pilot, it was needed to know who is responsible for a procedure. The Central Purchasing Body can be responsible of the procedure and the model until today's meeting did not reflect this clearly.
Before the modification the CPB actAs Buyer and is responsibleOf the procedure. The discussion went around the need to add or not the object property responsibleOf also between CPB and Procedure.

The WG final conclusion:

1.	Remove the property actAs
2.	CPB is a subclass of Buyer
3.	Remove the attribute and property related to the SubRoleType for the CPB. It inherits from buyer.

**JointProcurement discussion:**

The main question was how to express the leader of the procedure when it is a JointProcurement.
To have a consistent representation of the organisation roles in the case of Joint Procurement it was agreed to have role for the different organisations involved in an “OrganisationGroup”. Thus, the Group-member role was included in the epo:organisation-subrole code list.
Then Group Leader and Group Member are the expected roles for organisations within an “OrganisationGroup”.

It was decided to review the model in September.

**FrameworkAgreementTechnique Discussion**

The discussion started with whether a lot uses frameworkAgreementTechnique in a frameworkAgreement.
As the FrameworkAgreement establishes a Technique then a FrameworkAgreementTechnique is ConcludedBy a FrameworAgreement. The inverse property was missing in the model.

The WG agreed on the addition of “epo:concludesFrameworkAgreementTechnique”.

**Pending topics for the mappings of current TED Forms:**

*  Tender Validity Duration:

During past sessions of WG it was discussed about “SubmissionTerm” attributes, where TenderValidityDuration was deleted and it was only kept the ValidityEndDate with data type Date.

As in the Validity is representing a period, the data type Date was not correct in the model. It was changed to ValidityPeriod. As the period Includes EndDate and DurationMeasure the needs of the mapping are covered.

*  SecurityClearanceTerm:

It was necessary to reformulate the “Deadline” definition for the SecurityClearanceTerm to represent better what is needed and requested by the CA when tendering.
The definition was changed to: “The time limit by which the security clearance must be received.”

The meeting ended with a brief discussion about the BDTI

**Action Point:**

- To do an exercise for the phases and other needs of the BDTI (Procedure, Proceduretype, Buyer/CPB, Role-Organisation, Location/Address, Nuts, Lot)