== Working Group meeting 15/10/2020

Participants: Paloma Arillo Aranda, Natalie Muric, Roberto Reale, Helder Santos, Juan Carlos Segura, Giampaolo Sellitto, Jalini Srisgantharajah, and Enric Staromiesjki.

**Topic of discussion: Roles and Subroles**

The approach of the meeting was focused on the discussion of roles and subroles. The meeting started with the last decisions made on the 13th of October.

The WG continues with the review of the generic diagram and worked on it:

See the Award Reification diagram:

link:https://github.com/OP-TED/ePO/blob/feature/frozen-2.0.2/implementation/test/roles-as-classes/ePO-CM-roles-as-classes.eap[ePO CM roles as classes]

From the discussion of the diagram the following decisions were made:

* The WG decided to change ProcurementInvolvement by ProcurementSituation. This class is connecting the agent to a particular role.
* The WG the need or not to have the class PlannedProcurementPart within the generic diagram (see above). It comes from a previous analysis of when procurement is in the planning phase or whether it has been planned and design in terms of procedure, lots, etc,. When mapping ontology to eForms we needed to model the planning phase in the procurement. The WG concluded that this class is not needed in the diagram because in the end it will not exist and the class was removed.
* The association property was changed because it should go from ProcurementSituation to Period and cardinality 0..1
* The WG discussed the involvesActivity (activity-type). For example, there is an awards contract activity and there are two roles, the buyer and the winner, so how to know that this activity is related to one of the roles. With a query, the activity and the role and agent performing that activity is retrieved.
* The generic class owl:Thing was removed after discussion with the WG. The specialisation of ProcurementSituation profile the situation, meaning by profile that extends and customises the situation. One customization could be the restriction of cardinality, and one example of example could that the AwardDecision needs to extend the subcontract.
* The Buyer class was removed from the Award-Reification diagram and the property from AwardDecision to Winner was renamed by epo:hasWinner 0..1 instead of epo:involvesWinner. Also, the property AwardDecision involvesBuyer Buyer was removed.
* The bidirectional property from Subcontract to AwardDecision was modified. Instead to say AwardDecision epo:isReferredToIn Subcontract, and Subcontract epo:acceptsProposalOf AwardDecision, the direction was changed saying that AwardDecision epo:acceptsProposalOf Subcontract, and Subcontract epo:refersToAwardDecision AwarDecision. Moreover, the WG saw that already exist in the model that Subcontract refersToAwardResult AwardDecision, and AwardDecision has Subcontract. This property was removed since the bidirectional  property AwardDecision epo:acceptsProposalOf Subcontract, and Subcontract Subcontract epo:refersToAwardDecision AwarDecision means the same.
* The property from ContractAwardNotice to AwardDecsion was also changed to notifiesAwardDecision instead of notifiesAwardResult, and the multiplicity was changed from 1 to 1..*.
* The property refersTo from ProcurementSituation to Lot was also removed.
* The meeting ends with the discussion if the AwardDecsion is the reification class.