== Please find below the minutes of the 03rd of September.

Participants: Ana Aido, Paloma Arillo Aranda, Cécile Guasch, Hilde Kjølset, Giorgia Lodi, Thor Møller, Natalie Muric, Juan Carlos Segura Fernández-Carnicero, Giampaolo Sellitto, Jalini Srisgantharajah and Enric Staromiejski.


**Topic of discussion: Mappings TED forms - Standard Form 17 (Defence), section III.2 Conditions for participation**

OP asked the business people, whether they could check in their respective countries if the conditions for participation are used as selection or exclusion criterion. OP indicates that this is a need found doing the mappings to the TED forms and it is not represented in the model due eForms is not going into this detail.

The discussion about this topic was to use the “ProcurementCriterion” to instantiate these type of criteria. The WG detected a problem if the “ProcurementCriterion” is used because it is an abstract class and therefore querying the criteria the data retrieved will be from selection and exclusion criterion. Therefore, there is no way to differentiate it. The WG indicated that the conclusion was that the concept should be placed in exclusion criterion with a note that this is only used in the specific case of this standard form.

**Topic of discussion: Group of economic operators**

OP explained that in the TED forms mappings to the ePO Ontology there is the need to know how a tenderer is a group of economic operators. Currently, the mapping is through the property “isMemberOf”. The WG indicates that the correct mapping is thought the inheritance property therefore the mapping is:

* Tenderer isA Economic Operator, Economic isA Role, EconomicOperator isRoleOf OrganisationGroup.

OP also asked if the address to be provided is the address of the group or the address of each member. The WG check the form and said that the address of each member is the one to be provided, then how it is possible to know that it pertains to the same group. The WG explained that as the contract number is repeatable in the form but can only be awarded to one winner, whilst different winners (as in FrameworkAgreement) should have different ContractNumbers. When the Contractor is repeated it means that it belongs to the same winner (as in a Consortium).

**Topic of discussion: Definitions**

The terms defined and the actions can be consulted at https://github.com/eprocurementontology/eprocurementontology/blob/meetings/ePO_definitions.xlsx.
