== Please find below the minutes of the 23rd of April:

**Participants:** Paloma Arillo Aranda, Vibeke Engesaeth, Maria Font, Cécile Guasch, Giorgia Lodi, Thor Møller, Natalie Muric, Roberto Reale, Helder Santos, Juan Carlos Segura, and Jalini Srisgantharajh.

**Topic of Discussion:**

Mappings (https://github.com/OP-TED/ePO/blob/feature/frozen-2.0.2/analysis_and_design/eforms_mapping/Ontology_eForms_Mapping_New%20Regulation.xlsx)

During the meeting the followings BTs were discussed: BT-71 and BT-79

**Topic of Discussion:** Definitions

During the meeting the WG worked on the definitions of the Procurement Criterion. The definition decided for this concept was:

_A criterion specific to Procurement._

_Additional Information:_

_This Procurement Criterion can be only Exclusion Ground, Selection Criterion or Award Criterion. Each of these criteria can contain subcriteria (Criterion class)._

During the creation of the definition of the Procurement Criterion, the WG detected that the attribute Procurement Criterion Applicability is not needed since it already used in the Selection Criterion and Exclusion Ground.

**Action Points**:

- @everis to change the mapping of the Procurement Criterion Appplicability based on its usage in the Seclection Criterion and Exclusion Ground.