== Working Group meeting 22/10/2020

Participants: Ana Aido, Cécile Guasch, Giorgia Lodi, Roberto Reale, Helder Santos, Juan Carlos Segura, Giampaolo Sellitto, and Enric Staromiejski.

**Topic of discussion: eOrdering**

The WG continued the discussion from the 20th of October concerning electronic ordering terms.
The idea that we may be in front of two different patterns or models emerged a couple of times: one for
_ex-ante_ "rules and terms" (e.g. what needs to be done for eOrdering), and another for _ex-post_ "situations" (what
was actually done during the eOrdering). The general feeling of the WG was, however, that both situations are very complicated
and that there should be one single and coherent model to represent both situations. The WG had the feeling that the eProcurement process will need information
about the ex-ante and ex-post, maybe having two reification class, but this needs more discussions.

The analysis of "Ordering Terms" led to consider whether the class "Term" could become a reification class or not, since some of the attributes
of the class seem to be necessary in the reification (at least those referring to Agent and Role). This analyses was not covered during the meeting, since
the WG ran out of time. It was proposed to take examples from invoicing to complete the analysis in subsequent meetings, since the Invoice may
have more terms and data relating Agent to Role and, possibly, to other data necessary in the reification. Cécile Guash commited to send examples on
this (which we did: see CG email to the WG, subject "example invoice", 22 Oct. 17:25).

From this meeting the main discussed points were:

* The WG though that we need to have the ex-ante assignment of roles to agents because it is needed for the notification phase
(a class RoleAssignment was originally proposed for this, but was not added to the UML diagram since it needs further analysis). This
assignment would be differentiated from the Terms in eOrdering.
* The WG saw examples of ordering and some roles involved in it. Looking to the examples, the WG saw that it is possible to map them with
the current model, but there is more content where we will need to add more entities to the model to cover the entire Ordering data that may
or may not be related to eOrdering Terms.
** The WG saw also from the example the possible need to add the 'Period' which is an informational data. This Period should be part of the
reification ordering class.
** Comparing what is in UBL and CEN TC 440, the WG thought that maybe it is not needed to map the XML models to the ePO is not possible nor
convenient. Thus, for example,  according to one of these XML-based models, the delivery term has an attribute "location", whilst in ePO we
already have the class Location.
* The WG agrees that as soon we come up with a solution we need to test it immediately with real data samples.