== Working Group meeting 28/01/2020

Participants: Paloma Arillo, Ana-Maria Babaligea, Cécile Guasch, Giorgia Lodi, Vibeke Engesaeth, Thor Møller, Natalie Muric, Roberto Reale, Juan Carlos Segura, Jalini Srisgantharajah and Enric Staromiejski.

The approach of the meeting on the 28th January was focused on the everis’ presentation regarding the “Planning” mappings and the “Agent” class.

Everis started the meeting explaining its proposal for Planning. Everis explained that the problem discovered doing the mappings to eForms is that some classes cannot be mapped through the PlannedProcurementPart class and therefore the mapping goes through the Procedure in order to arrive to the Lot. A disjoint has been added between the property that links the PIN with the Procedure and the property that links the PIN with the PlannedProcurementPart. Regarding these possible options of the mappings (through the PlannedProcurementPart or Procedure) the WG worked in the following rule in order to know when to go from one or from the other one:

* In PIN Time-limit the Notice will contain a reference either to PlannedProcurementPart or conversely to Procedure (both are disjoint, see also the diagram Planning). This implies that for PIN Time-limit it is necessary first to discern the existence of one of these classes to know how to get to specific information. For example, some ContractTerms properties like PlaceOfPerformance could be reached either starting from PlannedProcurementPart or through the Lots linked to the Procedure.

Once the Planning mapping proposal was approved by the WG, the second half of the meeting was focused on the everis presentation of the usage of “agent” class instead of the “organization” class.
Everis explained that we need to have an “agent” class in ePO which should be an extension of an Agent class of a Core Agent Vocabulary from SEMIC. Everis explained that this Core vocabulary does not exist yet, but as everis is now contractor of SEMIC for the maintenance and evolution of some core vocabularies, they want to propose it. Everis explained that this new vocabulary is needed since the FOAF one does not allow proper reuse for ePO. The FOAF Agent class does not have a very good level of granularity in terms of properties and therefore a new Agent vocabulary would extend the FOAF agent class with more properties.

Everis explained that they are proposing to use the Agent class instead of the organization because in ePO there is the need to represents not only Organizations, also Persons and systems. This proposition was more or less approved by the WG, however, they need that everis shares an example where the class Organization was used in the past and where the Agent class is used now.

**Action Points: **

* @everis: add a WG comment each time a PIN Time Limit  has 2 options this needs to be reflected also in the discussion maybe show the comment.
* @everis: use of the INSPIRE directive for addresses in order to know how to use the Location class and how to improve the Address adding attributes from UBL, the same as SEMIC is doing in its Core Vocabularies.
* @everis: check the mappings and put in black the mappings that come from “Competition” and therefore were already reviewed.
* @everis: Compare contact point and the communication channel, and think how the Electronic can be treated as a contact a point.
* @everis: think about the stereotypes used in the Organization model
* @everis: Share with the WG the comparison between the usage of the class Organization (old diagram) and the class Agent (new proposal)
* @WG: Reply to the issues created regarding the definitions of the Strategic Procurement (https://github.com/eprocurementontology/eprocurementontology/issues/227), Social Procurement (https://github.com/eprocurementontology/eprocurementontology/issues/229), Innovative Procurement (https://github.com/eprocurementontology/eprocurementontology/issues/228)and Green Procurement (https://github.com/eprocurementontology/eprocurementontology/issues/230).