== Working Group meeting 03/06/2021

Participants: Paloma Arillo Aranda (OP), Cécile Guasch (ISA2 - DIGIT), Hilde Kjolset (dfø), Giorgia Lodi (ISTC-CNR), Thor Steiner Møller (dfø), Natalie Muric (OP) and Giampaolo Sellitto (ANAC).

**Topic of discussion: Check Summary from 01 June 2021 and update decisions**

* *Contract has no relation with Value in v2.0.2 but does in 2.0.1.*

Proposal: rename ‘Value’ to ‘MonetaryValue’ in the new version of the Ontology (this new version will incorporate updates to definitions and predicates with regard to 2.0.1, and will add certain features from 2.0.2). We have to consider the implication of this change for all mappings, such as ANAC Data, Consip Data and TED Data.

* **Maximum and Minimum** were proposed to be used as predicates in 2.0.1 and 2.0.2.

* The predicate ‘hasAwardEstimatedValue’ cardinality should be changed to ‘0 .. *’

* We have to identify all ‘MonetaryValue’ instances in the model to link them to other classes.

* The following point was brought up: If there is an AwardedValue for the FrameworkAgreement and an AwardedValue for the Contract, is that not a contradiction because the FrameworkAgreement is a Contract?

FrameworkAgreement: either has no value and the value is of the contracts derived from it, or it is considered to be the total value of the FrameworkAgreement. Otherwise one ends up with a double value.

A comparison of these concepts in the model and the Business Terms in eForms and current forms need to be drawn up to check and ensure that the WG creates a model that reflects the use cases of both, current forms and eForms.

**Topic of discussion: Amount**

* It might be possible to eliminate the class Amount by inserting an amount:numeric and currency:skos in the MonetaryValue. It must be checked if the same can be done for Amount and Quantity.

* In the TED mappings the data is mapped to ‘ccts’ and not ‘epo’ as per the OWL file.

* When checking notice 2020/S 243-602968 it was noted that the minimum and maximum offer is used, which is different to the maximum and minimum value of the contract and should probably be associated to the tender as shown in the model created in the last meeting.

**Topic of discussion: Plans for the near future**

* Apply the Reification on the whole model.

* Finalize eOrdering and eCatalogue

* Add the ESPD to the Ontology once an ESPD UML data model is available.

* Ensure there is placeholder in the Ontology conceptual model for indicating data during the contract’s life cycle.