== Working Group meeting 31/08/2021


*Date:* 31/08/2021 +
*Participants:* Paloma Arillo Aranda (OP), Eugeniu COSTETZKI (Meaningfy), Giorgia Lodi (ISTC-CNR), Natalie Muric (OP), Andrea PASARE (Meaningfy) and Giampaolo Sellitto (ANAC)
*Model editor:* Eugeniu Costetchi  +
*Note editor:* Andreea Pasăre

=== Topics

==== Comments in EA

The additional info and the date added in the descriptions of the ePO could be transformed and added as part of the element? To be checked.

==== Queries

ePO is the Ontology for Public Procurement. The BDTI is a pilot project set up with ISA2 in order to enable linking open data: to be able launch SPARQL queries from the data base different databases. The goal is to transform the ePO into RDF as other ontologies. The main issue is the transformation: respect data format, do the mapping, try to connect and link the data from the three countries participating in the BDTI project (Italy, Portugal and Norway).

Giorgia had done a test launching a query in the BDTI. The WG tries to launch also a query in GraphDB. The test has to be done again when we have the updated data.

The WG updates the query live and runs a test:

In the EPO “isResponsiblityOf’ should be corrected to ‘isResponsibilityOf’

Amount: in the ePO data ’Amoun’t uses ‘ctts’ instead of ‘epo’ what should be considered in the query

In the TED data lot ‘hasContractAwardedValue’ not ‘LotAwardedValue’.

It has to be paid attention when the ePO uses data different to the one used in the queries.

We add currencyCode to the query

We add the date

If we want the indicator, we need the ‘hasAcceleratedProcedure’

The query launched will belong to the BDTI queries, as it is this project, which will use it.  In the ideal world, the query could be used by other datasets.

==== GitHub issues update

The following issues have been discussed and updated

Issue 105 Combination Lot –Tender type – updated and closed.

Issue 104 Glossary Change description code – closed.

Issue 103– closed.
