== Please find below the minutes from the 04th of March.

Participants: Ana Aido, Paloma Arillo Aranda (OP), Cécile Guasch (ISA2 - DIGIT), Veit Jahns (TC440), Giorgia Lodi (ISTC-CNR), Natalie Muric (OP), Helder Santos (INCM), Juan Carlos Segura Fernández-Carnicero (everis), and Enric Staromiejski (everis).

**Topic of discussion: Competency Questions**

* The WG analysed and modified some of the competency questions created by everis for the validation of the converted notices produced in the context of TED RDF project.

**Topic of discussion: eCatalogue**

* The WG discussed the CatalogueSituation and the fact if this refers to the Pre-award or Post-award catalogue situation. The TC440 convenor indicates that the current model is closer to the Post-award than to the Pre-award situation. This led to rename the reificantion class to indicate that it addressed the Postaward situation (the class is now 'PostawardCatalogueSituation').

* The WG asked if for the different types of catalogue situations there will be different roles involved. The model is more or less the same, at least at the structual level. The difference would be in the roles and the objects (things involved) , since in the preaward the catalogue involves the Tenderer (and the lot) whilst in the post-awared it involves the seller and the contract.

* After examining definitions of eCatalogue, namely the ones proposed by the TC440 convenor, Open PEPPOL and UBL, the WG came up with its own definition of 'eCatalogue':

"A document describing a set of items offered for purchase that can be processed in an electronic way.

Additional Information

The description may include a rich set of details, like prices, packaging, discounts, special promotions, etc."

* The WG also defined the class 'Item' as:

"A singular product or service.

Additional Information

An item can be an atomic thing or a composition of things that together are seen as a unit, e.g. a tetrabrik of milk or an indivisible package of six tetrabriks."

The latest diagram on the eCatalogue is the following one:

link:https://github.com/OP-TED/ePO/tree/feature/frozen-2.0.2/implementation/test/roles-as-classes/img/eCatalogueReification_04032021.png[eCatalogue Reification]

This diagram will evolve with the results from further discussion on how to go on in the structuring of the eCatalogue (to be addressed in forthcoming sessions).