== Please find below the minutes from the 02nd of March.

Participants: Paloma Arillo Aranda (OP), Hilde Kjølset (dfø), Natalie Muric (OP), Fatima Sadiq (OP), Helder Santos (INCM), Juan Carlos Segura Fernández-Carnicero (everis), Giampaolo Sellitto (ANAC), Jalini Srisgantharajah (dfø), and Enric Staromiejski (everis).

**Topic of discussion: Reification class**

During the meeting the WG discussed the usage of the reification class. The following points were discussed:

* The WG reviewed the ProcurementTermsNotificationSituation. This class was created specially to reflect which roles related to terms are involved  at notification time.
* Since terms are notably present in the diagrams Competition and Results, the WG asked whether this reification should not also appear in those diagrams and how.
* Note that this reification could not be used in any other situations, but that this could be the subject of further analysis
* In a first round of analysis on this, the WG thought of changing the name of the ProcurementTermsNotificationSituation by InformationProvisionSituation to reflect those roles that provide documents/information, (as this reification is used mainly to explain who is providing information during the the procurement). However, on second thought, the WG considered that the InformationProvisionSitutation is not needed at all, since for these 'kind of roles' like the tax information provider, employment information provider, etc. only the name and the contact point are actually required. This need is already covered by the generic reification "ProcurementSituation". Hence, the WG decided to remove the specialisation (InformationProvisionSituation) completely.
* During the meeting, some questions were though to know which kind of info would be retrieve from the RDF triple store.
* The WG worked started to consider how to include the Procurement Situation reification class in the Competition diagram, and test its effects and relations with the classes currently existing in this Diagram.