== Working Group meeting 29/04/2021

Participants: Paloma Arillo Aranda (OP), Cécile Guasch (ISA2 - DIGIT), Hilde Kjolset (dfø), Giorgia Lodi (ISTC-CNR), Natalie Muric (OP), Helder Santos (INCM) and Giampaolo Sellitto (ANAC).

**Topic of discussion: Conventions report**

Short summary concerning the conventions report version 2.0.1 and the project conversion of notices from xml format to rdf.

**Topic of discussion: Definitions - predicates**

The following relations were discussed and compared with the html conventions to see if this work will correct the inconsistencies:

* Subject: SecurityClearanceTerm

Object: Winner

Predicate: applies

It was decided to remove this relationship as it is not required.  If any such relationship is required in the future it should be studied within its use case.

* Subject: TenderLot

Object: LotGroup

Predicate: appliesTo - renamed to ‘isSubmittedFor’

Definition: Relation showing that a TenderLot is submitted for a group of lots

Inverse: hasTenderLot

Definition: Relation indicating a GroupLot has a TenderLot associated to it

* Subject: SelectionCriterion

Object: LotGroup, Lot

Predicate: ‘appliesTo’ renamed to ‘isSpecifiedIn’

Definition: Relation indicating a selection criterion in a given Lot or LotGroup

Inverse: specifies

Definition: Relation that indicates the conditions for selecting economic operators for tendering

* Subject: Contract

OBJect: Document

Predicate: attaches

Definition: Relation indicating that a Thing includes a document

Inverse: isAttachedIn

Definition: Relation indicating a document is included in a Thing

* Subject: Tender

Object: TenderDocument (inherited from Document) change in Model

Predicate: attaches

Definition: Relation indicating that a Thing includes a document

Inverse: isAttachedIn

Definition: Relation indicating a document is included in a Thinbj
* Subject: Buyer and its relations are correct. No need to review.
