== Working Group meeting 13/04/2021

Participants: Paloma Arillo Aranda (OP), Giorgia Lodi (ISTC-CNR), Natalie Muric (OP), Helder Santos (INCM) and Giampaolo Sellitto (ANAC).

**Topic of discussion: Definitions**

The following concepts were defined in the meeting:

* epo:Amount

Definition: A number of monetary units specified using a given unit of currency

* epo:UnitCodeListAgencyID - attribute renamed to epo:CurrencyCodeListAgencyID

Definition:  Identifier of the agency that maintains the currency code list used

* epo:UnitCodeListAgencyName - attribute renamed to CurrencyCodeListAgencyName

Definition: Name of the agency that maintains the currency code list used

* epo:UnitCodeListID - attribute renamed to epo:CurrencyCodeListID and its data type changed to URI

Definition: Concept scheme URI used for the currency code list

* epo:BuyerProfileNotice

Definition: Notice of the existence of a buyer profile

* epo:Contractor

Definition: An economic operator that has signed a contract with a purchaser

* epo:EvaluationBoard

Definition: Committee set up to evaluate the tenders submitted

Additional information: The committee may be a regular board or a jury.

* epo:ExpressionOfInterest

Definition: Document presenting an economic operator's request to be considered for procedures covering a specific domain

The definitions will be added to the ePO Glossary and the EAP file.