= Working Group meeting

*Date*: 10/08/2024     +
*Participants***:** Eugen Costetchi, Achilles Dougalis, Grzegorz Kostkowski, Natalie Muric, Andreea Pasare, Giovanni Paolo Sellitto  +
*Model editor:* Achilles Dougalis    +
*Note editor:* Eugen Costetchi, Grzegorz Kostkowski


== Agenda

* Discuss WGM schedule
* Discussing eEvaluation module
* eEvaluation report


== Discussion

* The schedule for the WG meetings for October was discussed, it was posted on the ePO WG Microsoft Teams channel.
* A draft of the Ontology Requirements Specification Document (ORSD) for the upcoming eEvaluation module was created.
** Specifically, regarding the Roles for evaluation:
*** It was clarified that AdmittedCandidates for the evaluation process  are not Tenders.
*** It was clarified that the Winner of the evaluation does not always become the Contractor.
*** It was clarified that  Buyer can be a  ContractingEntity or ContractingAuthority as there is no differentiation of these concepts in the Ontology.
** It was noted that the evaluation report is internal (confidential) and not public, however certain data in the evaluation report may become open to the tenderers when notifying them on the result of the tenders/qualification submission.
** It was decided that evaluation and submission shall be discussed in parallel.
** It was noted that the winner and the contractor are likely out of scope of eEvaluation.
** Samples of evaluation reports from Italy were received to be studied for eEvaluation.
** It was confirmed that both public and private (non-public) reports have same structure and content.
** It was clarified that an Evaluation Committee consists of people (natural person) and some usual roles of an Evaluation Committee
**  were identified: president, member, secretary, expert.
** In the context of the authored _eEvaluation ORSD _document, it was noted that use cases are derived from the activity description.
** It was verified that formal checks may or may not be a duty of an Evaluation Committee (depends on the organization of an Evaluation Committee)
** It was briefly explained how rejection of all the competitors is handled. The procedure depends on a decision of a contracting authority: it can revise a call for tender or go for another procedure. In addition, it was noted that cases of single bidders or a single competitor causes a red flag to be raised. This is currently out of scope for this module. More information can be found https://www.eca.europa.eu/en/publications/sr-2023-28[here.]


== Action Points

* Clean up the current _eEvaluation ORSD _draft document



