== Working Group meeting   +
*Date*: 16/01/2024    +
*Participants:* ** **Paloma Arillo, Natalie Muric, Maneva Petkova, Ewa Salarnier, Dragos Stoica, Pascaline  Laure Tchienehom, Theokritos Zafeiriou  +
*Model editor:* Andreea Pasăre   +
*Note editor:* Achilles Dougalis


=== Agenda

* Collecting eSubmission requirements.

In the first instance, eSubmission will be based on the ESPD Response. We would like your input concerning use cases on data coming from ESPD Responses.

=== Discussion

* It was explained at the beginning that the eSubmission is based on ESPD Response. It was noted that eSubmission is much wider that the ESPD Response.
* It was explained that the eProcurement Ontology covers end-to-end procurement and for each module there is a starting point. In the case of eSubmission that is the ESPD Response.
* A presentation was given on the existing ePO conceptual models.
* The draft of the use case and data exchange document was presented:
** It was noted that in the case of a 2 phase procedure at the qualification phase there is not a tender yet, but a Candidate. Therefore the Tenderer text was changed to Candidate/Tenderer test.
* Went through UBL terms from https://docs.ted.europa.eu/ESPD-EDM/latest/_attachments/ESPD_CM_html/index.html[ESPD-EDM Response Technical Overview] :
|===
|*UBL Business Term* |*ESPD definition* |*Comment*

|*cac::QualificationApplicationResponse* |A document issued by a procurement organisation to notify an Economic Operator whether it has been admitted to or excluded from the tendering process.

Business element: ESPDResponse

25/11/2021 |to be implemented as epo-sub:ESPDResponse as a specialisation of epo:Document
|cbc::ContractFolderID |Business element: ReferenceNumber
An identifier, assigned by the sender, for the process file (i.e., record) to which this document belongs.

ESPD definition: an identifier that is specified by the buyer and used as a reference number for all documents in the procurement process.
Additional comments: a reference to the procurement procedure to which a Qualification request document and the delivered response documents are associated.

14/09/2021 |technical attribute not to be implemented in ePO
|cbc::CustomizationID |Business element: BusinessProcessTypeIdentifier
Identifies a user-defined customization of UBL for a specific use.

ESPD definition: identifies the identification scheme for the notice (ESPD XML instance, eForms*), specifically the schemeAgencyID (value "CEN-BII", mandatory) and the schemeVersionID.
Additional comments: we use the value “urn:www.cenbii.eu:transaction:biitrdm070:ver3.0”.

13/09/2021 |technical attribute not to be implemented in ePO
|cbc::EconomicOperatorGroupName |Business element: ConsortiumName
Economic Operator Group Name associated with this Response document.

ESPD definition: the name of the group that presents a tender to which this Economic Operator belongs (e.g. the name of a consortium, a joint venture, etc.).

14/09/2021 |It was noted that each member of the Consortium will provide an ESPD Response, also the Subcontractors need to be taken into consideration.
Name of the Organisation Group that the Economic Operator belongs to.
|cbc::ID |Business element: DocumentIdentifier
An identifier for this document, assigned by the sender.

ESPD definition: an identifier for this document, normally generated by the system that creates the ESPD document, or the organisation responsible for the document (e.g. the buyer, or the supplier, e.g. an economic operator). The identifier enables positive referencing the document instance for various purposes including referencing between transactions that are part of the same process, or referencing multiple versions of the ESPD document.
Additional comments: compulsory use of schemeAgencyID attribute, in order to identify the organisation responsible for the document.

13/09/2021 |ESPD Response document identifier
|cbc::IssueDate |Business element: DocumentIssueDate
The date, assigned by the sender, on which this document was issued.

ESPD definition: date when the document was issued by the buyer.
Additional comments: format "YYYY-MM-DD".

14/09/2021 |#should it be date of dispatch? epo:hasDispatchDate
ESPD-EDM team should check if this is issued or dispatch.#
|cbc::IssueTime |Business element: DocumentIssueTime
The time, assigned by the sender, on which this document was issued.

ESPD definition: time when the document was issued by the buyer.
Additional comments: format "hh:mm:ss".

14/09/2021 |#should it be date of dispatch? epo:hasDispatchDate
ESPD-EDM team should check if this is issued or dispatch.#
|cbc::PreviousVersionID |Business element: PreviousDocumentVersionIdentifier
Identifies the previous version of the Response document which is superceded by this version.

ESPD definition: the version identifying the previous modification of the content of this document.

14/09/2021 |#ESPD-EDM team should provide an use case for PreviousVersionID.#
|cbc::ProcedureCode |Business element: ProcedureCode
A code signifying the type of this tendering procedure.

ESPD definition: the type of the procurement administrative procedure according to the EU Directives.
Additional comments: this information will be linked to eForms.

14/09/2021 |this is the procedure type.
|cbc::ProfileExecutionID |Identifies an instance of executing a profile, to associate all transactions in a collaboration.
Business element: ESPDVersionIdentifier |technical attribute not to be implemented in ePO
|cbc::ProfileID |Business element: SpecificationIdentification
An identification of the specification containing the total set of rules regarding semantic content, cardinalities and business rules to which the data contained in the instance document conforms.

ESPD definition: n/a
Additional comments: the identification may include the version of the specification as well as any customizations applied.

13/09/2021 |technical attribute not to be implemented in ePO
|cbc::UBLVersionID |Business element: UBLVersionIdentifier
Identifies the earliest version of the UBL 2 schema for this document type (besides the ones from the extension) that defines all of the elements that might be encountered in the current  instance.

ESPD definition: n/a

13/09/2021 |technical attribute not to be implemented in ePO
|cbc::UUID |Business element: DocumentUniversallyUniqueIdentifier
A universally unique identifier for an instance of this document.

ESPD definition: a universally unique identifier that can be used to reference this ESPD document instance; this UUID will be used to link the ESPD Response to its corresponding ESPD Request (thus its compulsoriness).
Additional comments: copies of a document must be identified with a different UUID; compulsory use of schemeAgencyID attribute.

14/09/2021 |ESPD Response document epo:hasUUID
|cbc::VersionID |Business element: DocumentVersionIdentifier
Indicates the current version of the Request document.

ESPD definition: the version identifying the content of this document.
Additional comments: changes in content should entail the modification of the version identifier and a reference to the previous version.

14/09/2021 |ESPD Response document epo:hasVersion
|cbc:CopyIndicator |Business element: CopyIndicator
Indicates whether this document is a copy (true) or not (false).

ESPD definition: this component enables to keep track of the event of having forwarded the same document several times to the same or to different destinations.
Additional comments: copies of an ESPD document should be identified with distinct UUIDs.

14/09/2021 |#on hold until ESPD-EDM team will check further.
there is a contradiction between the two definitions provided in ESPD.#
| | |
|*cac::AdditionalDocumentReference* |A reference to an additional document

Business element: Notice

30/11/2021 |epo:Document epo:associatedWith (or create a subproperty for this at the level of ESPD Response)
|cbc::DocumentDescription |Text describing the referenced document

Business element: DocumentDescription |dct:description
|cbc::DocumentType |The type of document being referenced, expressed as text.

Business element: NoticeTypeDescription

26/11/2021 |#In ePO we do not need to map to the docrefcontent-type since the type of document exists already as a concept.
NB: there is a typo in name of the codelist in the ESPD-EDM technical overview.#
|cbc::DocumentTypeCode |The type of document being referenced, expressed as code.

Business element: NoticeTypeCode

26/11/2021 |#In ePO we do not need to map to the docrefcontent-type since the type of document exists already as a concept.
NB: there is a typo in name of the codelist in the ESPD-EDM technical overview.#
|cbc::ID |A reference to an additional document associated with this document.

Business element: NoticeIdentifier

26/11/2021 |adms:identifier at the level of the additional document.
|cbc::IssueDate |The date, assigned by the sender of the referenced document, on which the document was issued.

Business element: NoticeIssueDate

26/11/2021 |#should this be epo:hasPublicationDate since we are referring to things that are published?
ESPD-EDM team should check if "publication" is the right word instead of "issue".#
|cbc::IssueTime |The time, assigned by the sender of the referenced document, at which the document was issued.

Business element: NoticeIssueTime

26/11/2021 |#should this be epo:hasPublicationDate since we are referring to things that are published?
ESPD-EDM team should check if "publication" is the right word instead of "issue".#
|cbc::UUID |An identifier for the referenced document.

Business element: NoticeUUID

26/11/2021 |epo:hasUUID
|cbc::DocumentTypeCode |link to at-voc:docref-content-type |#In ePO we do not need to map to the docrefcontent-type since the type of document exists already as a concept.
NB: there is a typo in name of the codelist in the ESPD-EDM technical overview.#
| | |
|*cac::ExternalReference* |A reference to an attached document that is external to the document(s) being exchanged.
Business element: ExternalReference |ePO only provides the URI for the attached document.
|cbc::Description |Text describing the external object.

Business element: Description

26/11/2021 |epo:Document dct:description
|cbc::FileName |The file name of the external object.

Business element: Name

26/11/2021 |ePO does not provide external objects.
|cbc::URI |The Uniform Resource Identifier (URI) that identifies the external object as an Internet resource.

Business element: URI

26/11/2021 |epo:Document epo:hasAccessURL
| | |
|*cac::ProcurementProjectLot* |One of the procurement project lots into which this contract can be split.

Business element: ProcurementProjectLot

25/11/2021 |implemented as epo:Lot
|cbc::ID |An identifier for this procurement project lot.

Business element: LotReference

26/11/2021 |adms:identifier at the epo:Lot level
| | |
|*cac::ProcurementProject* |A class to describe a project to procure goods, works, or services.

Business element: Procedure |implemented as epo:Procedure
|cbc::Description |Text describing this procurement project.

Business element: Description |dct:description at the epo:Procedure
| | |
|*cac::Party* |A class to describe an organisation, sub-organisation, or individual fulfilling a role in a business process.

Business element: Organisation

25/11/2021 |epo:AgentInRole
|cac::PartyIdentification/cbc::Identifier |An identifier for the party; the PartyIdentification UBL class has an associated basic element "cbc:ID".

Business element: Identifier

25/11/2021 |adms:identifier of the Organization that plays that specific Role.
|cac::PartyName/cbc::Name |A name for this party; the PartyName class has an associated basic element "cbc:Name" .

Business element: Name

25/11/2021 |epo:hasLegalName of the Organization that plays that specific Role.
|cbc::EndPointID |An identifier for the end point of the routing service (e.g., EAN Location Number, GLN).

Business element: EndPointID

25/11/2021 |epo:AgentInRole epo:exposesChannel epo:hasIdentifier
|cbc::WebsiteURI |The Uniform Resource Identifier (URI) of the organization website; i.e., its Uniform Resource Locator (URL).

Business element: PartyWebsite

25/11/2021 |epo:hasInternetAddress of the Organization that plays that specific Role.
| | |
|*cac::ServiceProviderParty* |A class to describe a party contracting to provide services, such as transportation, finance, etc.

Business element: ServiceProvider

25/11/2021 |this is a specialisation of cac::Party
| | |
|*cac::ContractingParty* |A class to describe an individual, a group, or a body having a procurement role in a tendering process.

Business element: Buyer

25/11/2021 |this is a specialisation of cac::Party
|cbc::BuyerProfileURI |The buyer profile is typically located on a web site where the contracting party publishes its procurement opportunities

Business element: BuyerProfile

26/11/2021 |epo:Buyer epo:hasBuyerProfile
| | |
|*cac::EconomicOperatorParty* |The Economic Operator issuing the Qualification Application Response.

Business element: EconomicOperator

25/11/2021 |this is a specialisation of cac::Party
|cac::QualifyingParty/Party/cbc::IndustryClassificationCode |This party's Industry Classification Code.

Business element: IndustryClassificationCode

25/11/2021 |#is there a typo in this ESPD-EDM attribute? Should it be cac::Party?
epo:Business epo:hasBusinessSize at-voc:economic-operator-size#
|cbc::IndustryClassificationCode |link to at-voc:economic-operator-size |epo:Business epo:hasBusinessSize at-voc:economic-operator-size
| | |
|*cac::EconomicOperatorRole* |A class to describe the tenderer contracting role.

Business element: EconomicOperatorRole

25/11/2021 |this can be inferred from epo:OrganisationGroup epo:hasMember (epo:leadBy) org:Organization;
ePO team to check all values from codelist at-voc:eo-role-type and see if they map to ePO roles.
|cbc::RoleCode |Business element: EconomicOperatorRoleCode
A code specifying the role of the party.

ESPD definition: identifies the role of the Economic Operator in the bid.

17/09/2021 |.
|cbc::RoleDescription |Business element: EconomicOperatorRoleDescription
A textual description of the party role.

ESPD definition: n/a.

27/09/2021 |.
|cbc:RoleCode |link to at-voc:eo-role-type |.
| | |
|*cac::QualifyingParty* |A class to describe the distinctive features or characteristics qualifying an economic operator to be a party in a tendering process (e.g., number of employees, number of operating units, type of business, technical and financial capabilities, completed projects).

Business element: QualifyingParty

25/11/2021 |*from technical handbook:* is used to place data about the economic operator that is available from an official list, tenderer register or (pre)qualification system, such as official classification schemes, certificates, the number of employees, references used for the classification, etc.;
ePO needs to model a Pre-QualificationSystemData that includes the properties from ESPD-EDM model for cac::QualifyingParty
|cac::BusinessClassificationScheme/cbc::Description |Business element: BusinessClassificationScheme
The classification scheme used for the business profile; the BusinessClassificationScheme UBL class has an associated basic element "cbc:Description".

ESPD definition: the text describing one official classification assigned by an official list or (pre)qualification system to the Economic Operator.

17/09/2021 |.
|cac::CompletedTask/cbc::Description |Business element: CompletedTask
Text describing this completed task; the CompletedTask UBL class has an associated basic element "cbc:Description".

ESPD definition: text describing the works, supplies or services executed, delivered or performed in a procurement project (normally used as a reference for the classification of the Economic Operator).

17/09/2021 |.
|cac::FinancialCapability/cbc::ValueAmount |Business element: GeneralTurnover
A financial capability of this qualifying party; the FinancialCapability UBL class has an associated basic element "cbc:ValueAmount".

ESPD definition: a monetary amount as a measure of this capability.

17/09/2021 |link to epo:MonetaryValue
|cac::Party/cac::PartyIdentification/cbc::ID |Business element: QualifyingAgencyIdentifier
An identifier for the party; the PartyIdentification UBL class has an associated basic element "cbc:ID".

ESPD definition: the identifier of the Economic Operator in an official list, register or (pre)qualification system; the attribute schemeAgencyID must hold the value retrieved from eCertis that identifies unequivocally the (pre)qualification system.
Additional comments: if, for any reason, that value is not available use the default schemeAgencyID "EU-COM-GROW" and the cac:PartyIdentificaton for the value of the identifier; additionally, use the data structure “registered” to specify an alternative or additional name, identifier and description; the code list EOIDType should be used to indicate the type of identifier used as a value of the schemeID attribute, e.g. schemeID="VAT".

17/09/2021 |The Economic Operator ID at the level of a Pre-qualification system
|cbc::EmployeeQuantity |Business element: EOEmployeeQuantity
The number of people employed by this qualifying party.

ESPD definition: the number of people employed by the economic operator participating in the tender

17/09/2021 |link to epo:Quantity
| | |
|*cac::Person* |A class to describe a person.

Business element: RepresentativeNaturalPerson

25/11/2021 |person:Person
|cac::CitizenshipCountry/cac::Country/cbc::IdentificationCode |The country of the person's citizenship.

Business element: CountryCode

18/11/2021 |
|cbc::BirthDate |This person's date of birth.

Business element: RepresentativeNaturalPersonBirthDate

25/11/2021 |
|cbc::BirthplaceName |The name of the place where this person was born, expressed as text.

Business element: RepresentativeNaturalPersonBirthplace

25/11/2021 |#typo: p should be capital letter#
|cbc::FamilyName |This person's family name.

Business element: RepresentativeNaturalPersonFamilyName

25/11/2021 |
|cbc::FirstName |This person's given name.

Business element: RepresentativeNaturalPersonFirstName

25/11/2021 |
|cbc::NationalityID |An identifier for this person's nationality.

Business element: RepresentativeNaturalPersonNationality

25/11/2021 |
| | |
|*cac::PowerOfAttorney* |A class to describe a power of attorney.

Business element: PowerOfAttorney

25/11/2021 |in ESPD-EDM is a specialisation of cac::Person
in ePO this can be modelled as an epo:AgentInRole epo:playedBy a person:Person
|cbc::Description |Business element: RepresentativeNaturalPersonRoleDescription
Text describing this power of attorney.

ESPD definition: Idem.

20/09/2021 |
|===



* This Thursday we will discuss eAccess as now it belongs to the ePO maintenance.




=== Action Points

* Cells highlighted in #yellow# in the table above are to be addressed by the ESPD-EDM project.
* ePO action points:
** Model cac::PowerOfAttorney as an epo:AgentInRole epo:playedBy a person:Person.
** Model a Pre-QualificationSystemData that includes the properties from ESPD-EDM model for cac::QualifyingParty.
** Check all values from codelist at-voc:eo-role-type and see if they map to ePO roles.
** Check that a Subcontractor role can be part of an OrganizationGroup, so it can also submit its own ESPD Response.

