= *D02.02: Project Charter proposal*

== *Document Metadata*

[cols="1,3"]
|===
|Date 
|2017-08-03

|Status
|Accepted

|Version
|1.0

|Authors 
|Makx Dekkers - AMI Consult
Emidio Stani - PwC EU Services
Florian Barthélemy - PwC EU Services

|Reviewed by 
|Nikolaos Loutas - PwC EU Services
Natalie Muric - Publications Office of the EU

|Approved by 
|Natalie Muric - Publications Office of the EU
|===

*This report was prepared for the Publications Office of the European Union by:*
_PwC EU Service_

--
*Disclaimer*

The views expressed in this report are purely those of the authors and may not, in any circumstances, be interpreted as stating an official position of the European Commission.
The European Commission does not guarantee the accuracy of the information included in this study, nor does it accept any responsibility for any use thereof.
Reference herein to any specific products, specifications, process, or service by trade name, trademark, manufacturer, or otherwise, does not necessarily constitute or imply its endorsement, recommendation, or favouring by the European Commission.
All care has been taken by the author to ensure that s/he has obtained, where necessary, permission to use any parts of manuscripts including illustrations, maps, and graphs, on which intellectual property rights already exist from the titular holder(s) of such rights or from her/his or their legal representative.
--
Note: this Project Charter is an adaptation of the Project Charter template of PM² V2.5.



include::partial$feedback.adoc[]