= *1 CONSIDERATIONS ON THE BUSINESS CASE*

Public procurement represents around 20% of GDP in Europe. This big buying volume offers a high economic potential to enhance efficiency of European procurement. The EU is investing significantly on the digitalisation of the public procurement process (referred to as e-procurement). This goes beyond simply moving to electronic tools; it rethinks various pre-award and post-award phases with the aim to make them simpler for businesses to participate in and for the public sector to manage. It also allows for the integration of data-based approaches at various stages of the procurement process.

Directive 2014/24/EU on public procurement, Directive 2014/25/EU on procurement by entities operating in the water, energy, transport and postal services sectors, and Directive 2014/23/EU on the award of concession contracts establish rules on the procedures for procurement by contracting authorities with respect to public contracts, design contests and concessions, requiring contracting authorities in the EU to publish notices above certain thresholds. Directive 2014/55/EU on electronic invoicing in public procurement5 defines the requirement for a European standard for electronic invoices, while the Commission Implementing Regulation (EU) 2015/19866 specifies standard forms for the publication of notices in the Official Journal of the European Union.Article 6 of the Regulation states that either the eNotices online application or the TED eSender systems should be used to electronically transmit notices to the Publications Office of the European Union. From a different angle, the implementation of the revised PSI directive7 across the EU is calling for open, unobstructed access to public data in order to improve transparency and to boost innovation via the reuse of public data. 

Procurement data has been identified as data with a high-reuse potential. Therefore, making this data available in machine-readable formats, following the data as a service paradigm, is required in order to maximise its reuse. 
Given the increasing importance of data standards for e-procurement, a number of initiatives driven by the public sector, the industry and academia have been kick started in the recent years. Some have grown organically, while others are the result of standardisation work. The vocabularies and the semantics that they are introducing, the 
phases of public procurement that they are covering, and the technologies that they are using all differ. These differences hamper data interoperability and thus its reuse by them or by the wider public. This creates the need for a common data standard for publishing public procurement data, hence allowing data from different sources to be 
easily accessed and linked, and consequently reused. 

In this context, the Publications Office of the EU aims to develop an e-procurement ontology. The objective of the e-procurement ontology is to act as this common standard on the conceptual level, based on consensus of the main stakeholders and designed to encompass the major requirements of the e-procurement process in conformance with the Directives and Regulation mentioned above.
