= *Annex I: USE CASES TO BE DEVELOPED BY THE WORKING GROUP*
* e-tendering process: 
https://github.com/eprocurementontology/eprocurementontology/issues/8
* Analysing e-procurement procedures, 
https://github.com/eprocurementontology/eprocurementontology/issues/11
* Increase cross-domain interoperability in terms of (financial) exclusion grounds
among Member States, 
https://github.com/eprocurementontology/eprocurementontology/issues/13
* Public understandability (Use case to be derived from interviews with transparency watchdogs and similar stakeholders) 
* Monitor the money flow, 
https://github.com/eprocurementontology/eprocurementontology/issues/9
* Detect fraud and compliance with procurement criteria, 
https://github.com/eprocurementontology/eprocurementontology/wiki/Add-a-new-use-case
* Alerting services, 
https://github.com/eprocurementontology/eprocurementontology/issues/10
* Introduce automated classification systems in public procurement (not a real use case but a set of ideas for classification systems to be gathered) 
* Businesses need to participate in procurement, 
https://github.com/eprocurementontology/eprocurementontology/issues/15
* Buyers need to buy things, which means following the e-procurement phases,
https://github.com/eprocurementontology/eprocurementontology/issues/15. This 
use case includes (and therefore could be breakdown into other use cases at a lower granular level):
** Creating new information (e.g. description of the procurement, giving points for award criteria).
** Reusing information from different databases and domains, such as
* business registries (to reduce administrative burden and ensure consistency of information); and
* tax, social payments, etc. systems (to verify that potential contractors meet selection criteria).
** (Sending information to other systems to ensure transparency etc. requirements are met, e.g. contract registers).
* Other public entities are directly involved in the e-procurement phases, 
https://github.com/eprocurementontology/eprocurementontology/issues/15. This use case includes (and therefore could be breakdown into other use cases at a lower granular level):
** Creating new information (e.g. review authority freezing the procurement process, rejecting a complaint, or awarding damages).
** Exchanging data between e-procurement systems and systems used by auditors and review bodies, so that it is easier for them to check the validity of the procurement process.
** Regulators (ministries, review bodies, etc.), citizens, journalists, NGOs, academics, buyers, etc. use the data to answer policy-relevant questions, 
https://github.com/eprocurementontology/eprocurementontology/issues/15. This use case includes (and therefore could be breakdown into other use cases at a lower granular level): 
** Accessing information created by the use cases above.
** Accessing information created specifically to be used only in this use case.
** Connecting this information with other information, in particular:
* budget systems (to answer questions linked to following the money). 
(Note: e-invoicing is not included in this section, because it falls within the scope of "e-procurement phases described in the Project Charter", i.e. the first use cases in this list.); and
* contract registers (to allow answering more sophisticated questions, e.g. linked to the full text of contracts).
* Analyse the success rate of the procurement process and the reasons for failure, 
as well as estimate the costs associated, 
https://github.com/eprocurementontology/eprocurementontology/issues/16
* Long term analysis about the evolution of procurement activities in the EU Institutions, 
https://github.com/eprocurementontology/eprocurementontology/issues/16
* Providing information for Contract Registries, 
https://github.com/eprocurementontology/eprocurementontology/issues/18
* Enable the publication of notices as linked open data to enable the exploitation of the corresponding data through the semantic web in ways yet to be envisaged, 
https://github.com/eprocurementontology/eprocurementontology/issues/18