= *Transformation of the eProcurement UML model into a formal OWL ontology*
Adapted from the document, link:https://github.com/meaningfy-ws/model2owl/blob/master/doc/uml2owl-transformation/uml2owl-transformation.pdf[Transformation of the eProcurement UML model into a formal OWL ontology, 20 May 2020.]

The link:https://www.uml.org/[UML] to link:https://www.w3.org/OWL/[OWL] transformation rules were finalised on the 20 May 2020. The results can be read in detail in the document via the link: link:https://github.com/meaningfy-ws/model2owl/blob/master/doc/uml2owl-transformation/uml2owl-transformation.pdf[Transformation of the eProcurement UML model into a formal OWL ontology, an Initiative for developing eProcurement Ontology]

== *Introduction*

Following the format of information presentation in the document, this reference consists of four sections covering the following general UML topics:

* Classes and attributes
* Main connector types: associations, dependencies, and generalisations
* How the datatypes and enumerations should be transformed 
* Transformation rules applicable to all UML elements regarding comments, labels, and notes.

Each section provides a table with overview of the transformation rule set it describes. The table is displayed in three columns, one for each layer of the ontology architecture:

* the in-core ontology layer, 
* the in-data shape layer, and
* the in-reasoning layer.

Transformation rules are specified in normative language and are aided by proto-typical UML diagram fragments, usually preceding the rule, along with representation of the corresponding OWL fragment depicted in Graffoo visual notation.

The diagrams are provided side to side to assist understanding, with the UML fragment on the left constituting the source of the transformation, and the OWL fragment on the right representing the result of the transformation.

Each transformation rule is accompanied by the formal OWL representation, in link:https://www.w3.org/TeamSubmission/turtle/[Turtle, Terse RDF Triple Language] and RDF/XML syntaxes, corresponding to the UML fragment depicted in the preceding figure. RDF/XML is a syntax to express RDF graphs as an XML document. Turtle is a compact textual syntax for RDF [18] that resembles a natural text form with abbreviations for common usage patterns and datatypes.


include::partial$feedback.adoc[]