= *Transformation of UML connectors*

In this section are specified transformation rules for UML association, generalisation and dependency connectors. Table 2 provides an overview of the section coverage.

== *Unidirectional association*

A binary Association specifies a semantic relationship between two member ends represented by properties. Please note that in accordance with specification [5], the association end names are not obligatory. However, we adhere to the UML conventions [7], where specification of at one member ends, for unidirectional associ-ation, and two member ends, for bidirectional association, is mandatory. Moreover, provision of a connector (general) name is discouraged.

.Transformation rules overview for UML connectors

[cols="1,1,1,1"]
|===
s|UML element|Rules in core ontology layer|Rules in data shape layer|Rules in reasoning layer

`s|Association* 
|Rule 11
|
|

s|Association domain*
|
|
|Rule 12

s|Association range*
|
|Rule 14
|Rule 13

s|Association multiplicity*
|
|Rule 15
|Rule 16,17

s|Association asymmetry*
|
|Rule 18
|Rule 19

s|Association inverse
|
|
|Rule 20

s|Dependency
|Rule 11
|
|

s|Dependency domain 
|
|
|Rule 12

s|Dependency range
|
|Rule 34
|Rule 33

s|Dependency multiplicity
|
|Rule 15
|Rule 16

s|Class generalisation 
|Rule 21
|
|

s|Property generalisation
|Rule 22
|
|

s|Class equivalence
|
|
|Rule 23

s|Property equivalence 
|
|
|Rule 24
|===

*Rule 11* (Unidirectional association - in core ontology layer). Specify object prop-erty declaration axiom for the target end of the association.

Insert fig 10 pg 20

[cols="1,1"]
|===

a|
[source,turtle]
:relatesTo a owl:ObjectProperty ;
    rdfs:label "relates oo"@en;
    skos:definition "Description of the relationship meaning"@en;
.
a|
[source, rdf]
<owl:ObjectProperty rdf:about="http://base.uri/relatesTo">
    <rdfs:label xml:lang="en">relates to</rdfs:label>
    <skos:definition xml:lang="en">Description of the relationship meaning</skos:definition>
</owl:ObjectProperty>

s|Listing 33: Property declaration in Turtle syntax
s|Listing 34: Property declaration in RDF/XML syntax
|===

== *Association Source*

*Rule 12* (Association source  in reasnoning layer). Specify object property domain for the target end of the association.

[cols="1,1"]
|===

a|
[source,turtle]
:relatesTo a owl:ObjectProperty ;
    rdfs:domain :ClassName ;
.
a|
[source, rdf]
<owl:ObjectProperty rdf:about="http://base.uri/relatesTo">
    <rdfs:domain rdf:resource="http://base.uri/ClassName"/>
</owl:ObjectProperty>

s|Listing 35: Domain specification in Turtle syntax
s|Listing 36: Domain specification in RDF/XML syntax
|===

== *Association Target:*

*Rule 13* (Association target - in reasoning layer). Specify object property range for the target end of the association.

[cols="1,1"]
|===

a|
[source,turtle]
:relatesTo a owl:ObjectProperty ;
    rdfs:range :ClassName ;
.
a|
[source, rdf]
<owl:ObjectProperty rdf:about="http://base.uri/relatesTo">
    <rdfs:range rdf:resource="http://base.uri/ClassName"/>
</owl:ObjectProperty>

s|Listing 37: Range specification in Turtle syntax
s|Listing 38: Range specification in RDF/XML syntax
|===

*Rule 14* (Association range shape - in data shape layer). Within the SHACL Node Shape corresponding to the source UML class, specify property constraints indicating the range class.

[cols="1,1"]
|===

a|
[source,turtle]
:ClassName a sh:NodeShape ;
    sh:property [
        a sh:PropertyShape ;
        sh:path :relatesTo ;
        sh:class :OtherClass ;
        sh:name "relates to" ;
    ];
.
a|
[source, rdf]
<sh:NodeShape rdf:about="http://base.uri/ClassName">
    <sh:property>
        <sh:PropertyShape>
            <sh:path rdf:resource="http://base.uri/relatesTo"/>
            <sh:name>relates to</sh:name>
            <sh:class rdf:resource="http://base.uri/OtherClass"/>
        </sh:PropertyShape>
    </sh:property>
</sh:NodeShape>

s|Listing 39: Property class constraint in Turtle syntax
s|Listing 40: Property class constraint in RDF/XML syntax
|===

== *Association multiplicity*

*Rule 15* (Association multiplicity - in data shape layer). Within the SHACL Node Shape corresponding to the source UML class, specify property constraints indicating minimum and maximum cardinality according to cases provided by Rule 8.

[cols="1,1"]
|===

a|
[source,turtle]
:ClassName a sh:NodeShape ;
    sh:property [
        sh:path :relatesTo;
        sh:minCount 1 ;
        sh:name "relates to" ;
    ] ;
.
a|
[source, rdf]
<sh:NodeShape rdf:about="http://base.uri/ClassName">
    <sh:property>
        <sh:PropertyShape>
<           sh:path rdf:resource="http://base.uri/relatesTo"/>
            <sh:name>relates to</sh:name>
            <sh:minCount rdf:datatype="http://www.w3.org...#integer">1</sh:minCount>
        </sh:PropertyShape>
    </sh:property>
</sh:NodeShape>

s|Listing 41: Min cardinality constraint in Turtle syntax
s|Listing 42: Min cardinality constraint in RDF/XML syntax
|===

*Rule 16* (Association multiplicity - in reasnoning layer). For the association target multiplicity, where min and max are different than "*"" (any) and multiplicity is not [1..1], specify a subclass axiom where the source class specialises an anonymous restriction of properties formulated according to cases provided by Rule 9.

[cols="1,1"]
|===

a|
[source,turtle]
:ClassName a owl:Class ;
    rdfs:subClassOf [ a
        owl:Restriction ;
        owl:minCardinality"1"^^xsd:integer;
        owl:onProperty :relatesTo ;
    ] ;
.
a|
[source, rdf]
<owl:Class rdf:about="http://base.uri/ClassName">
    <rdfs:subClassOf>
        <owl:Restriction>
            <owl:onProperty rdf:resource="http://base.uri/relatesTo"/>
            <owl:minCardinality rdf:datatype="http://www.w3.org...#integer" >1</owl:cardinality>
        </owl:Restriction>
    </rdfs:subClassOf>
</owl:Class>

s|Listing 43: Min cardinality restriction in Turtle syntax
s|Listing 44: Min cardinality restriction in RDF/XML syntax
|===

*Rule 17* (Association multiplicity "one" - in reasnoning layer). If the association multiplicity is exactly one, i.e. [1..1], specify functional property axiom like in Rule 10.

[cols="1,1"]
|===

a|
[source,turtle]
:relatesTo a owl:FunctionalProperty .
a|
[source, rdf]
<rdf:Description rdf:about="http://base.uri/relatesTo">
    <rdf:type rdf:resource="http://...owl#FunctionalProperty"/>
</rdf:Description>

s|Listing 45: Declaring a functional property in Turtle syntax
s|Listing 46: Declaring a functional property in RDF/XML syntax
|===

== *Recursive association*

In case of recursive associations, that are from one class to itself, the transformation rules must be applied as in the case of regular unidirectional association, which are from Rule 11 to Rule 17. In addition the association must be marked as asymmetric expressed in Rule 19.

*Rule 18* (Association asymmetry  in data shape layer). Within the SHACL Node Shape corresponding to the UML class, specify SPARQL constraint selecting instances connected by the object property in a reciprocal manner.

Insert fig 11 pg 25

[cols="1,1"]
|===

a|
[source,turtle]
:ClassName a sh:NodeShape ;
    sh:sparql [
        sh:select """
            SELECT ?this ?that
            WHERE {
            ?this :relatesTo ?that .
            ?that :relatesTo this .
            }""" ; ] ;
.
a|
[source, rdf]
<sh:NodeShape rdf:about="http://base.uri/ClassName">
    <sh:sparql rdf:parseType="Resource">
        <sh:select>
            SELECT ?this ?that
            WHERE {
            ?this :relatesTo ?that .
            ?that :relatesTo ?this .}
        </sh:select>
    </sh:sparql>
</sh:NodeShape>

|Listing 47: Declaring an asymmetric property in Turtle syntax
|Listing 48: Declaring an asymmetric property in RDF/XML syntax
|===

*Rule 19* (Association asymmetry - in reasoning layer). Specify the asymmetry object property axiom for each end of a recursive association.

[cols="1,1"]
|===

a|
[source,turtle]
:relatesTo a
    owl:AsymmetricProperty .
a|
[source, rdf]
<rdf:Description rdf:about="http://base.uri/relatesTo">
    <rdf:type rdf:resource="http://...owl#AsymmetricProperty"/>
</rdf:Description>

s|Listing 49: Declaring an asymmetric property in Turtle syntax
s|Listing 50: Declaring an asymmetric property in RDF/XML syntax
|===

Insert fig 12 pg 26

== *Bidirectional association*

The bidirectional associations should be treated, both on source and target ends, like two unidirectional associations. The transformation rules from Rule 11 to Rule 17 must be applied to both ends. In addition these rule the inverse relation axiom must be specified.

*Rule 20* (Association inverse - in reasoning layer). Specify inverse object property between the source and target ends of the association.

[cols="1,1"]
|===

a|
[source,turtle]
:relatesTo owl:inverseOf
    :isRelatedTo .
a|
[source, rdf]
<owl:ObjectProperty rdf:about="http://base.uri/relatesTo">
    <owl:inverseOf rdf:resource="http://base.uri/isRelatedTo"/>
</owl:ObjectProperty>

s|Listing 51: Declaring an inverse property in Turtle syntax
s|Listing 52: Declaring an inverse property in RDF/XML syntax
|===

'''
== *Unidirectional dependency*
The UML dependency connectors should be transformed by the rules specified for
UML association connectors.

'''
== *Class generalisation*

Generalisation [5] defines specialization relationship between Classifiers. In case of UML classes it relates a more specific Class to a more general Class. UML generalisation set [5] groups generalizations; incomplete and disjoint constraints indicate that the set is not complete and its specific Classes have no common instances. The UML conventions [7] specify that all sibling classes are by default disjoint, therefore even if no generalisation set is provided it is assumed to be implicit.

insert fig 13 pg 27

*Rule 21* (Class generalisation - in core ontology layer). Specify subclass axiom for the generalisation between UML classes. Sibling classes must be disjoint with one another.

[cols="1,1"]
|===

a|
[source,turtle]
:ClassName rdfs:subClassOf
        :SuperClass.
:OtherClass rdfs:subClassOf
        :SuperClass;
    owl:disjointWith :ClassName ;
.
a|
[source, rdf]
<owl:Class rdf:about="http://base.uri/ClassName">
    <rdfs:subClassOf rdf:resource="http://base.uri/SuperClass"/>
</owl:Class>
<owl:Class rdf:about="http://base.uri/OtherClass">
    <rdfs:subClassOf rdf:resource="http://base.uri/SuperClass"/>
    <owl:disjointWith rdf:resource="http://base.uri/ClassName"/>
</owl:Class>

s|Listing 53: Sub-classification in Turtle syntax
s|Listing 54: Sub-classification in RDF/XML syntax
|===

== *Property generalisation*

Generalization [5] defines specialization relationship between Classifiers. In case of the UML associations it relates a more specific Association to more general Association.

insert fig 14 pg 28

*Rule 22* (Property generalisation - in core ontology layer). Specify sub-property axiom for the generalisation between UML associations and dependencies.

[cols="1,1"]
|===

a|
[source,turtle]
:hasSister rdfs:subPropertyOf
    :relatesTo .
:isSisterOf rdfs:subPropertyOf
    :isRelatedTo .
a|
[source, rdf]
<owl:ObjectProperty rdf:about="http://base.uri/hasSister">
    <rdfs:subPropertyOf rdf:resource="http://base.uri/relatesTo"/>
</owl:ObjectProperty>
<owl:ObjectProperty rdf:about="http://base.uri/isSisterOf">
    <rdfs:subPropertyOf rdf:resource="http://base.uri/isRelatedTo"/>
</owl:ObjectProperty>

s|Listing 55: Property specialisation in Turtle syntax
s|Listing 56: Listing 56: Property specialisation in RDF/XML syntax
|===

== *Class equivalence*

*Rule 23* (Equivalent classes - in reasnoning layer). Specify equivalent class axiom for the generalisation with equivalent or complete stereotype between UML classes.

insert fig 15 pg 29

[cols="1,1"]
|===

a|
[source,turtle]
:ClassName owl:equivalentClass
:SuperClass.

a|
[source, rdf]
<owl:Class rdf:about="http://base.uri/ClassName">
    <owl:equivalentClass rdf:resource="http://base.uri/SuperClass"/>
</owl:Class>

s|Listing 57: Class equivalence in Turtle syntax
s|Listing 58: Class equivalence in RDF/XML syntax
|===

== *Property equivalence*

*Rule 24* (Equivalent properties - in reasnoning layer). Specify equivalent property axiom for the generalisation with equivalent or complete stereotype between UML properties.

[cols="1,1"]
|===

a|
[source,turtle]
:hasSister owl:equivalentProperty
    :relatesTo .
:isSisterOf
    owl:equivalentProperty
    :isRelatedTo .
a|
[source, rdf]
<owl:ObjectProperty
        rdf:about="http://base.uri/hasSister">
    <owl:equivalentProperty
        rdf:resource="http://base.uri/relatesTo"/>
</owl:ObjectProperty>
<owl:ObjectProperty rdf:about="http://base.uri/isSisterOf">
    <owl:equivalentProperty rdf:resource="http://base.uri/isRelatedTo"/>
</owl:ObjectProperty>

s|Listing 59: Property equivalence in Turtle syntax
s|Listing 60: Property equivalence in RDF/XML syntax
|===

