= *Section 1: UML Visual Notation*

// ([3] G. Booch, J. Rumbaugh, and I. Jacobson. Uni_ed Modeling Language User
//Guide, The (2nd Edition) (Addison-Wesley Object Technology Series) . Addison-
//Wesley Professional, 2005. ISBN 0321267974.
//[5] S. Cook, C. Bock, P. Rivett, T. Rutt, E. Seidewitz, B. Selic, and D. Tolbert.
//Uni_ed modeling language (UML) version 2.5.1. Standard formal/2017-12-05,
//Object Management Group (OMG), Dec. 2017. URL https://www.omg.org/
//spec/UML/2.5.1.)//


== *Classes and Attributes:* 

#Insert graphic P7, Fig 1#

Figure 1 depicts simple, abstract and regular classes with and without attribute
speci_cations. Note that no class methods are ever employed as this document as
the transformations aim at data structures only.

=== *Datatypes and enumerations:* 

#Insert graphic P7, Fig 2#

Figure 2 depicts a primitive datatype and an enumeration. No complex datatypes
are depicted as they are treated in the same manner as classes are.

=== *Association, generalisation, and dependency:*

#Insert graphic P7, Fig 3#

Figure 3 depicts association, generalisation and dependency connectors as the only
ones necessary to model the eProcurement conceptual model.

'''
== *Graffoo visual notation*

This section provides the main Graffoo elements employed in this document. A
detailed description can be consulted in the OWL standard specfications [15] and
in the Graffoo user guide [9]. 

//Links:
//([15] B. Parsia, P. Patel-Schneider, and B. Motik. OWL 2 web ontology language
//structural speci_cation and functional-style syntax (second edition). W3C
//recommendation, W3C, Dec. 2012. http://www.w3.org/TR/2012/REC-owl2-
//syntax-20121211/.
//[9] R. Falco, A. Gangemi, S. Peroni, D. Shotton, and F. Vitali. Modelling owl
//ontologies with grffoo. In European Semantic Web Conference, pages 320_325.
//Springer, 2014.

=== *Graffoo elements: Insert Figure 4:*

Graffoo visual notation for classes, instances and datatypes Notation: 

#Insert Figure 5:#

Graffoo visual notation for object and data properties and generic links
•	A yellow rectangle with solid black border is used to declare classes. Solid black and labelled arrows are used to declare class axioms. 
•	A green rhomboid with solid black border is used to declare datatypes. Solid black and labelled arrows are used to declare class axioms.
•	A pink circle with solid black border is used to declare individuals. Solid black and labelled arrows are used to declare axioms and assertions among individuals.
•	A green solid line is used to declare data properties, where the empty circle at the
beginning identifies the property domain while the empty arrow at the end indicates the property range.
•	A blue solid line is used to declare object properties, where the solid circle at the beginning identifies the property domain while the solid arrow at the end indicates the property range.

include::partial$feedback.adoc[]