:doctitle: The Use of the ePO in The TED Open Data Service Pipeline 
:doccode: epo-main-prod-042
:author: NPJ
:authoremail: nicole-anne.paterson-jones@ext.ec.europa.eu
:docdate: June 2024


== The TED Open Data Service

The TED Open Data Service conversion process uses mapping suites to map ePO classes to the XML controlled values in notices.

The xml data in notices is based on business terms defined in the legislative directives governing public procurement, and the data in RDF format is based on classes defined in the eProcurement Ontology. 

The "pipeline" refers to the fact that the conversion process is continuously performing the conversion of TED notices in xml form into RDF format and storing them in the OP's RDf database, or triplestore, the CELLAR.

<insert simple diagramme>

It is only by translating the data into RDF format that they become usable as linked open data that can be queried from CELLAR's SPARQL endpoint using SPARQL query language.

To read the detailed process and access the technical resources, you can https://docs.ted.europa.eu/docs-staging/ODS/index.html[access the full documentation here].



