= *D04.07 Report on policy support for e-Procurement* 
== *e-Procurement ontology*

== *Document Metadata*

[cols="1,3"]
|===
|Property|Value

|Date
|2016-09-20

|Status
|Accepted

|Version
|1.00

|Authors
|Nikolaos Loutas – PwC EU Services
Brecht Wyns – PwC EU Services
Stefanos Kotoglou – PwC EU Services
Dimitrios Hytiroglou – PwC EU Services

|Reviewed by
|Pieter Breyne  – PwC EU Services
Natalie Muric – Publications Office 
Cecile Guasch – European Commission, DG DIGIT
Vassilios Peristeras – European Commission, ISA Programme

|Approved by
|Natalie Muric – Publications Office
|===

*This study was prepared for the ISA Programme by:*

_PwC EU Services_

*Disclaimer:*

The views expressed in this report are purely those of the authors and may not, in any circumstances, be interpreted as stating an official position of the European Commission.
The European Commission does not guarantee the accuracy of the information included in this study, nor does it accept any responsibility for any use thereof.
Reference herein to any specific products, specifications, process, or service by trade name, trademark, manufacturer, or otherwise, does not necessarily constitute or imply its endorsement, recommendation, or favouring by the European Commission.
All care has been taken by the author to ensure that s/he has obtained, where necessary, permission to use any parts of manuscripts including illustrations, maps, and graphs, on which intellectual property rights already exist from the titular holder(s) of such rights or from her/his or their legal representative.

include::partial$feedback.adoc[]