= *5. CONCLUSION AND NEXT STEPS*
The objective of this deliverable was to collect the necessary information for starting the development of the e-Procurement Ontology, whicjh is a commonly agreed OWL ontology that will conceptualize and formally encode information describing public procurement in a structured and machine readable format.

Towards achieving this goal, this document has identified use cases for the ePO. The use cases demonstrate how the ePO can foster transparency and help monitor public procurement, how it can promote innovation, and how it can interconnect different public procurement systems. Moreover, the target audience of the ePO has been identified. The target audience includes, but is not limited to, contracting authorities, economic operators, regulators and the media.

Besides the target audience and use cases, a key objective of this work was to identify existing data standards and reference data which are relevant for e-Procurement. An initial assessment was conducted to identify the extent to which these existing solutions could be reused in the ePO. The analysis showed that many solutions can be reused directly, that some may provide guidance for aligning, and that some may be used for reference.

Following the ISA process and methodology for developing semantic agreements, [7] as mentioned in chapter 2, a next step would be to set up an open working group. A call for participation will be sent to stakeholder communities, inviting them to take part in the work. Once the working group members have been identified, roles and responsibilities will be assigned. The working group chairs, editors and experts will execute the operational work for developing the specification. They will have to agree on the use cases proposed in this work or identify further use cases, identify information requirements, and propose a set of core concepts for the ePO, taking into account the analysis of existing initiatives as presented in chapter 4, and a further in-depth analysis. In order to support their work, a collaboration environment should be set up. 

The collaboration environment could be hosted on Joinup , an online platform developed by the European Commission to help public administrations find, share, reuse, and develop interoperability solutions. The platform would allow members of the working group to post and discuss issues, to share and review drafts of the ePO, and to communicate with each other in an open and efficient manner. A key task of the working group when developing the ePO, would be to define naming and identifier conventions. A persistent Uniform Resource Identifier (URI) would have to be identified for the classes and properties that are defined in the ontology. A review group could be established to challenge and validate the proposals of the working group. 


