= *1.	INTRODUCTION*

== *1.1. Context*

Public procurement represents around the 20% of GDP in Europe. This big buying volume offers a high economic potential to enhance efficiency of European procurement. 

The EU is investing significantly on the digitalisation of the public procurement process (referred to as e-Procurement). This goes beyond simply moving to electronic tools; it rethinks various pre-award and post-award phases with the aim of makng them simpler for businesses to participate in, and for the public sector to manage. It also allows for the integration of data-based approaches at various stages of the procurement process.

With e-Procurement, public spending should become more transparent, evidence-oriented, optimised, streamlined and integrated with market conditions. More specifically, e-Procurement offers a range of benefits such as:

•	significant savings for all parties, both businesses and the public sector;
•	simplified and shortened processes;
•	reductions in red-tape and administrative burdens;
•	increased transparency;
•	greater innovation;
•	new business opportunities by improving the access of all enterprises, including small and medium-sized enterprises (SMEs), to public procurement markets.

To deliver the aforementioned benefits, e-Procurement relies heavily on the exchange of data between the different systems supporting the procurement processes i.e., achieving end-to-end interoperability of public procurement processes and underlying systems, and on the availability and dissemination of procurement data to the wider public i.e., improving transparency and stimulating innovation and new business opportunities. 

As stated in the Commission Regulation 2015/1986 (EU), contracting authorities in the EU are legally required to publish notices above certain capital thresholds. Article 6 of that Regulation states that either the online eNotices application or the TED eSender systems should be used for electronic transmition of notices to the Publications Office of the European Union. From a different angle, the implementation of the/ a revised PSI directive across the EU is calling for open, unobstructed access to public data to improve transparency, and to boost innovation, via the reuse of public data. Procurement data has been identified as data with a high-reuse potential. Making this data available in machine-readable formats, #following the data as a service paradigm, #(what does this mean?)# is required in order to maximise its reuse. 

Data exchange, access, and reuse are key requirements for efficient and transparent end-to-end public procurement. Because of this, we observe a shift in focus from the definition of procurement process standards for system-to-system exchange, to the development of data standards for publishing e-Procurement data in open, machine-readable formats (see Chapter 4 Related Ontologies/Vocabularies and Projects). 

The key challenge is that procurement data exists in different systems across the European Union:

* the relations between the different concepts in the procurement chain and data flow are not fully documented, therefore data and data relationships cannot be reused directly in a flexible and comparable manner;
* some data has inherited formats from its paper origins leading to illogical business processes and incorrect conceptual models;
* different systems use different data formats therefore reuse of information is not always efficient; and
* taxonomies like CPV are often not used correctly which creates serious problems e.g., making it very difficult for SMEs to find suitable business opportunities.

Given the increasing importance of data standards for e-Procurement, a number of initiatives driven by the public sector, industry, and academia have been initiated in recent years. Some have grown organically, while others are the result of standardisation work. The vocabularies and the semantics that they introduce, the phases of public procurement that they cover, and the technologies that they use all differ. These differences hamper data interoperability and reuse. This creates the need for a common data standard for publishing procurement data, hence allowing data from different sources to be easily accessed and linked, and consequently reused. The e-Procurement ontology (henceforth referred to as the ePO) introduced by this study attempts to address this. 

== *1.2. Proposed solution*

The ultimate objective of the ePO is to deliver a common and agreed OWL ontology that will conceptualise, formally encode, and make available in an open, structured, and machine-readable format, data about public procurement. The onlotogy will cover the public procurement process from end to end, i.e. from notification, through tendering to awarding, ordering, invoicing and finally payment.

It is not the intention of the ePO to reinvent the wheel by redefining existing terms or processes, but rather to unify all existing practices, thus facilitating seamless exchange, access and reuse of data.

Process, Methodology and Technology discuss in detail the open process and methodology that will be followed for developing the ePO.

== *1.3. Scope*

This report does not focus on creating the specifications of the ePO, neither in the form of a conceptual data model nor as an OWL ontology. 

The scope  is to put together the information necessary to proceed with the specification of the ePO, including a process and methodology to be followed for the development of the ePO. The following activities are in scope of this work: 

* Identify the target audience and the key use cases for the ePO; 
* Document and analyse existing initiatives to discover overlaps and gaps, and identify which ones to reuse, and with which ones to align;
* Identify data and code lists that can be referenced by the ePO.

== *1.4. Structure of this document*

This document is structured in several sections. After describing the context, scope and the proposed solution in section 1, section 2 proposes a process and methodology to be followed and the technology to be used for the development of an e-Procurement Ontology. Section 3 identifies the main stakeholders impacted by the ePO or that should be involved in its development. It then describes the possible use cases that the ePO aims to address. In section 4, relevant existing data models and code lists are identified and analysed. Section 4 also assesses the extent to which existing works could be reused in the ePO. Section 5 concludes the report and identifies the next steps to be taken for the further development of the e-Procurement Ontology.   

== *1.5. Common working terminology*

[cols="1,2"]
|===
|Term|Definition

|Public procurement
|The process by which public authorities, such as government departments or local authorities, purchase work, goods or services from companies [1].

|e-Procurement
|e-Procurement is the conduction of the procurement process by means enabled by the internet [2].

|Call for Tenders
|Procedure of asking for bids to be submitted for the awarding of a contract [3].

|Pre-award phase
|e-Procurement process phases occurring up-until  the award of the contract (e-Notification, e-Access, e-Submission, e-Evaluation, e-Awarding) [4].

|Post-award phase
|Post-award phase	e-Procurement process phases occurring after the award of the contract (e-Ordering, e-Invoicing, e-Payment) [4].

|Data standard
|A structural metadata specification that describes or defines other data [ISO111179]. Structural metadata indicates how compound objects are put together [NISO]. It can consist of among others data models, reference data, and identifier schemas [5].

|Data model
|A data model documents and organizes data, how it is stored and accessed, and the relationships among different types of data. The model may be abstract or concrete [6].

|Conceptual data model
|The conceptual model enables to understand the meaning of the data model. Generally, the conceptual data model is the most important. The conceptual model does not specify how properties and associations are technically represented .

|Ontology  
|A formal naming and definition of the types, properties, and interrelationships of the entities that exist for a particular domain. In the context of this report, an ontology should be expressed in OWL as this is the format used by the Common Data Model of the CELLAR, in which the ePO will be implemented.

|Approved by
|Natalie Muric – Publications Office
|===
