== Please find below the minutes of the 10th September:

Participants: Ana Aido, Paloma Arillo Aranda, Hilde Kjølset, Giorgia Lodi, Thor Møller, Natalie Muric, Helder Santos, Juan Carlos Segura Fernández-Carnicero, Giampaolo Sellitto, Jalini Srisgantharajah and Enric Staromiejski.

**Topic of discussion: Mappings TED forms - Standard Form 17 (Defence), section III.2 Conditions for participation**

* The WG discussed the final decision on the conditions for participations topic discussed on the 3rd of September. The WG indicated that the conclusion was that the concept should be placed in exclusion criterion with a note that this is only used in the specific case of this standard form.

**Topic of discussion: Central Purchasing Body**

* The WG said that there is an issue created in GitHub discussing the CentralPurchasingBody.

* The WG proposes to reopen the discussion taking into account such issue in GitHub.

* The WG indicated that the CentralPurchasingBody is independent of the roles and subroles discussion. The WG agreed that the discussion of roles and subroles will take place after the eOrdering discussion on the 17th of September. The WG also agreed to discuss:  (1)roles and subroles diagram; (2)to test roles and subroles solution into EvaluationReport showing how the winner is represented; (3)how to address the Central Purchasing Body; (4)other buyers. Note that the point 1, 2 and 4 is in the context of the roles and subroles solution.

**Topic of discussion: Definitions**

* The WG decided to remove the code usage from the selection criterion class (hasApplicability). Instead of this code list, the decision was to create an indicator as an attribute of the class selection criterion (UsageNotYetKnown).

* The WG asked why the Procurement Criterion is used if there is a Criterion class in the core criterion and core evidence vocabulary (cccev). Everis and OP explained that as the cccev was under evolution, the decision was not to use the cccev and move all the classes to the epo namespace until there will be a stable version of the cccev. The WG also indicates that the ProcurementCriterion class is needed because some dependencies and properties are from the eProcurement domain and they cannot exist within the cccev.  Moreover, the WG argued that not only the selection and exclusion criteria are related to the Lot, the ESPD also relates the exclusion criteria to the Lot.

* The WG asked why the ProcurementCriterion has the attributes “name” and “description” if maybe the Criterion class has them. Everis will check if the criterion class has both attributes in the cccev

The terms defined and the actions can be consulted at https://github.com/eprocurementontology/eprocurementontology/blob/meetings/ePO_definitions.xlsx

**Action point:**

- To check whether cccev has name and description in criterion class.

- To implement the solution discussed about Standard Form 17 (Defence), section III.2 Conditions for participation