== Please find below the minutes of the 12th of May:

Participants: Ana Aido, Paloma Arillo Aranda, Cécile Guasch, Vibeke Engesaeth, Maria Font, Giorgia Lodi, Natalie Muric, Roberto Reale, Helder Santos, Juan Carlos Segura, Giampaolo Sellitto, and Jalini Srisgantharajh.

**Topic of discussion:**

Definitions (https://github.com/OP-TED/ePO/blob/2042074d3a7e21b69f2892b645511ad083c13a05/v2.0.1/01-Glossary/ePO-Glossary.xlsx)

During both meetings the following concepts were defined:

* epo:FormalOrganization
* epo:RegisteredOrganisation
* epo:RecurrenceIndicator (epo:ContractNotice)
* epo:PreferredPublicationDate (epo:Notice)
* epo:FormType (epo:Notice)
* epo:NotificationPhasesType (epo:Notice)
* epo:NotificationPhasesContentType. The enumeration name, the property and the mapping were changed.
* epo:DPSUsage (epo:DynamicPurchaseESystemTechnique)
* epo:DPSCondition (epo:DynamicPurchaseESystemTechnique)
* epo:ReceptionDate (epo:Document)
* epo:DispatchDate (epo:Document)
* epo:UUID (epo:Document)