== Workgroup meeting


*Date:* 21/09/2021 +
*Participants:* Cecille Guasch, Hilde Kjølset, Giorgia Lodi, Thor Steinar Møller, Giovanni Paolo Sellitto +
*Model editor:* Eugeniu Costetchi  +
*Note editor:* Andreea Pasăre

=== eSender role

==== Issue

_Currently missing in the ontology but present in the EU Vocabularies roles_

==== Alternative choices

* _Add the role _
* _Keep it out of the ontology_
==== Discussion

_Currently kept out of the ontology because it is not clear whether it is in the scope of the ontology. And if it is then it seems to be an organisation that sends notices through a system. But it seems to be a specialisation of the epo:ProcurementServiceProvider._

=== review requester role

==== Issue

_Currently missing in the ontology but present in the EU Vocabularies roles_

==== Alternative choices

* _Add the role _
* _Keep it out of the ontology_
==== Discussion

It seems to be a secondary role. This is relevant in the post-contract notice.  +
Possibly, when a contract award notice is published, it may mention if there are any requests for review.

==== Decision

Not to implement as a role but the DG-Grow shall be asked if there is justification. No evidence of its use has been found in the eForms.

=== participant role

==== Issue

_Currently missing in the ontology but present in the EU Vocabularies roles. _Alternative choices

* _Add the role _
* _Keep it out of the ontology_
==== Discussion

This role is ambiguous and should be first defined precisely, and likely re-labelled. In ePO v2.0.2 epo:CandidateShortlist epo:hasQualified ...

==== Decision

Not to implement as a role but the DG-Grow shall be asked if there is justification.

=== Title: sub-role table in EU Vocabularies

==== Issue

* _What does this table cover? Currently, the sub-roles are modelled as relations between (e.g. Buyer, ProcurementServiceProvider) and Lot, and other ones._
* _DG-Grow(ESDP) proposes a sub-roles table and there is another table proposed by GD-Grow (eForms)._
==== Discussion

Alignment attempt between EPO and ESPD and eForms.  +
Group Leader, Group Member are more roles than sub-roles.  +
The hypothesis of why roles and sub-roles were split:

* There was a focus on the pre-award / notification phase and therefore the roles are those that are relevant in that phase, and sub-roles are possibly also roles but for other phases.

The situations are anchored either in an obligation modality or in a temporal modality

* We record future commitments
* Or actual facts

Possible situations where “sub-roles: occur:

* Payment
* Informing
* Submission (two-stage procedure: 1. Request to participate, that has to be evaluated and then, 2. Submission of the actual tender)
* Evaluation

What we do not know:

* How to model the roles and sub-roles. We are missing the situation/context/phase.
* Sub-roles can be delegated by “main roles”
* The delegation shall be contextualised for a procedure