== Please find below the minutes from the 9th of March.

Participants: Paloma Arillo Aranda (OP), Cécile Guasch (ISA2 - DIGIT), Natalie Muric (OP), Helder Santos (INCM), Juan Carlos Segura Fernández- Carnicero (everis), Giampaolo Sellitto (ANAC), Jalini Srisgantharajah (dfø), and Enric Staromiejski (everis).

**Topic of discussion: Review of the minutes from the 2nd and 4th of March**

* Some corrections were done according to the WG comments.

**Topic of discussion: Definitions**

The following concepts were defined in the meeting (see definitions in the EAP file and in the ePO glossary):

* epo:AccessTerm
    ** epo:SomeProcurementDocumentRestrictedJustification
    ** epo:ProcurementDocumentLandingPage
* From the epo:Address class the following concepts were defined, mostly inspired by the definitions provided by UBL-2.3 :
    ** epo:AdditionalStreetName
    ** epo:BlockName
    ** epo:BuildingName
    ** epo:BuildingNumber
    ** epo:CityName
    ** epo:CitySubdivisionName
    ** epo:CountrySubentity
    ** epo:CountrySubentityCode
    ** epo:District

The definitions cna be consulted in the Glossary. See https://github.com/OP-TED/ePO/blob/2042074d3a7e21b69f2892b645511ad083c13a05/v2.0.1/01-Glossary/ePO-Glossary.xlsx.
