= Requirements gathering

The requirements gathering stage includes all preliminary and preparation work such as deciding the ePO version to be released, what contents are to be included the release, and tool set-up e.g., the creation of the necessary GitHub branches. Also in this stage, the requirements for the new ePO module are collected in the Ontology Requirements Specification Document (ORSD) by the working group. If no new module is required for this release then the ORSD will contain specifications for each of the updates required for existing modules. The ORSDs can be viewed xref:epo-home::stories.adoc[here]


== Business view

The detailed business workflow for the Requirements Gathering Stage is depicted in the diagram below.


image::requirements gathering [detailed].bmp[]
_Requirements Gathering business view diagram_


The business workflow with Stakeholders for the Requirements Gathering Stage is depicted in the diagram below



image::requirements gathering [stakeholders].bmp[]
_Requirements Gathering business view with stakeholders diagram_


In the “*Decide work goal & scope and release version*” business rocess, The product owner decides which ePO module will be developed, if any, and into which version the module will be released. The versioning follows a “X.Y.Z” format, where X is the major version number, Y the minor version number, and Z the patch version number. For more information on ePO versioning rules, consult https://docs.ted.europa.eu/epo-home/versioning.html[the versioning page]. Finally, in this business process, the product owner informs the development team which fixes to open GitHub issues will be implemented in the upcoming version. These GitHub issues are assigned the milestone related to the X.Y.Z release.

In the "*Prepare the publication space for the work*" business process, The product owner creates the GitHub release branches marked as “release/X.Y.Z” of the specific ePO version in the following GitHub repositories:

* The https://github.com/OP-TED/epo-conceptual-model[OP-TED/ePO-conceptual-model] repository, where the conceptual model and the SDS artefacts will be generated and will be reviewed.
* The https://github.com/OP-TED/ePO[OP-TED/ePO] repository, where the SDS artefacts to be published as a stable release will be moved once reviewed.
* The https://github.com/OP-TED/epo-docs[OP-TED/ePO-docs] repository where the contents of the website containing the SDS documentation will be moved and/or generated.


In the “*Configure the artefact transformation pipeline*“ business process, the development team Configures the model2owl transformation script on the release/X.Y.Z branch of the https://github.com/OP-TED/epo-conceptual-model[OP-TED/epo-conceptual-model]  repository in order for model2owl to correctly transform the conceptual model of the new release. The development team may need to make additional adjustments to the configuration files during the xref:Business Process workflow/stage3/stage3.adoc[“preparing SDS version release”] stage if needed (due to a bug for example). As a result of this business process, the SDS Generation Configuration Business Object is created.


In the "*Collect subject relevant material*" business process, the ePO working group starts to meet on a weekly basis to develop the new ePO release. In the first meetings the working group collects and analyses material relevant to the new ePO release such as reports, sample data, and specifications. All the resulting files from this process are stored on a https://eceuropaeu.sharepoint.com/:f:/r/teams/GRP-eProcurementOntologyWorkingGroup/Shared%20Documents/General?csf=1&web=1&e=GXRttd[drive in OP's Internal sharepoint]. As a result of this business process, the “ORSD Supplementary Material” business object is created.

In the "*Interview domain experts*" business process, the working group discusses the nature of the release. Specifically, the domain experts that are part of the working group describe the eProcurement processes that need to be modelled in detail and are interviewed by the development team in order to fill any missing information regarding the eProcurement process. During these sessions, domain experts may provide or point out additional ORSD supplementary material to the rest of the working group.

In the "*Writing ORSD*" business process, the development team writes the ORSD as Word document in https://eceuropaeu.sharepoint.com/:f:/r/teams/GRP-eProcurementOntologyWorkingGroup/Shared%20Documents/General?csf=1&web=1&e=GXRttd[in OP's Internal SharePoint] using the ORSD Supplementary Material, and the notes from the interviews with domain experts. The Ontology Requirements Specification Document (ORSD) Business Object is created as a result of this business process.

In the "*Review ORSD*" business process, The working group reviews the ORSD and provides feedback. This can happen during the WG meetings, via GitHub Issues or discussions on the https://github.com/OP-TED/ePO[OP-TED/epo] repository, via eMail or other channels.

In the "*ORSD consolidation*" business process, The development team integrates the feedback from the working group into the ORSD Word document and transcribes the document into an footnote:AsciiDoc[https://asciidoc.org] Asciidoc page placed in the https://docs.ted.europa.eu/epo-home/stories.html[release branch] on the ePO-docs] repository. This Process may be revisited in future stages, if an inconsistency was discovered during the review of the formal artefacts.

== Application and Technology view


The  diagram below describes all the artefacts involved in this stage using business (yellow), application (blue) and technology (green) layers. The Github Repositories branches that are used for this stage are also depicted as orange rectangles for reference purposes.

image::requirements gathering [concise].bmp[]
_Application and Technology Layers of the “Requirements Gathering” stage diagram_




The “Ontology Requirements Specification Document (ORSD)” Business Object as defined in the https://docs.ted.europa.eu/epo-home/methodology2024.html[ePO LOT methodology], is translated into two Data Objects (documents):

* The "Print optimised ORSD document, which is stored in the https://eceuropaeu.sharepoint.com/:f:/r/teams/GRP-eProcurementOntologyWorkingGroup/Shared%20Documents/General?csf=1&web=1&e=GXRttd[OP's Internal SharePoint] server along with the Supplementary ORSD documents.
* The "Web optimised ORSD document", which is stored in the https://github.com/OP-TED/epo-docs[OP-TED/ePO-docs] repository, as an https://asciidoc.org/[AsciiDoc] page. For an example  of an ORSD file in ePO, see https://github.com/OP-TED/epo-docs/blob/main/modules/ROOT/pages/stories_eAccess.adoc[here].

The diagram also describes how the SDS Generation Configuration Business Object is translated as the “Owl Configuration” Data Object representing the model2owl configuration files that are stored in the https://github.com/OP-TED/epo-conceptual-model[OP-TED/ePO-conceptual-model] repository. For an explanation of what these files contain and how to generate them see https://github.com/OP-TED/model2owl?tab=readme-ov-file#configuration[here]. For an example of the configuration files in ePO See https://github.com/OP-TED/ePO/tree/master/implementation/ePO_core/model2owl-config[here].

