== *Bibliography*

[1] Xml metadata interchange (xmi) specification: Version 2.5.1. Standard
formal/2015-06-07, Object Management Group (OMG), 2015. URL http:
//www.omg.org/spec/XMI/2.5.1.
[2] T. Berners-Lee, R. T. Fielding, and L. M. Masinter. Uniform Resource Identifier
(URI): Generic Syntax. RFC 3986, Jan. 2005. URL https://rfc-editor.org/
rfc/rfc3986.txt.
[3] G. Booch, J. Rumbaugh, and I. Jacobson. Unified Modeling Language User
Guide, The (2nd Edition) (Addison-Wesley Object Technology Series). Addison-Wesley Professional, 2005. ISBN 0321267974.
[4] S. O. Bradner. Key words for use in RFCs to Indicate Requirement Levels.
RFC 2119, Mar. 1997. URL https://rfc-editor.org/rfc/rfc2119.txt.
[5] T. Bray, M. Sperberg-McQueen, E. Maler, F. Yergeau, and J. Paoli. Extensible
markup language (XML) 1.0 (fifth edition). W3C recommendation, W3C, Nov.
2008. http://www.w3.org/TR/2008/REC-xml-20081126/.
[6] S. Cook, C. Bock, P. Rivett, T. Rutt, E. Seidewitz, B. Selic, and D. Tolbert.
Unified modeling language (UML) version 2.5.1. Standard formal/2017-12-05,
Object Management Group (OMG), Dec. 2017. URL https://www.omg.org/
spec/UML/2.5.1.
[7] E. Costetchi. eProcurement ontology architecture and formalisation specifications. Recommendation, Publications Office of the European Union, April
2020.
26
Bibliography eProcurement UML conceptual model conventions
[8] E. Costetchi. eProcurement uml conceptual model to owl ontology transformation. Recommendation, Publications Office of the European Union, April
2020.
[9] M. Dean and G. Schreiber. OWL web ontology language reference. W3C
recommendation, W3C, Feb. 2004. http://www.w3.org/TR/2004/REC-owl-ref-20040210/.
[10] M. Dekkers, E. Stani, B. Wyns, and F. Barthelemy. D02.01 - specification of
the process and methodology to develop the eprocurement ontology with initial
draft of the eprocurement ontology for 3 use cases. Deliverable SC378DI07171,
Publications Office of the European Union, 2017.
[11] M. Fowler. UML distilled: a brief guide to the standard object modeling language. Addison-Wesley Professional, 2004.
[12] M. Grunninger. Enterprise modelling. In Handbook on enterprise architecture,
pages 515–541. Springer, 2003.
[13] N. Guarino, D. Oberle, and S. Staab. What is an ontology? In Handbook on
ontologies, pages 1–17. Springer, 2009.
[14] H. Knublauch and D. Kontokostas. Shapes constraint language (SHACL). W3C
recommendation, W3C, July 2017. https://www.w3.org/TR/2017/REC-shacl-20170720/.
[15] J. Kunze and T. Baker. The dublin core metadata element set. Technical
report, RFC 5013, August, 2007.
[16] A. Layman, T. Bray, H. Thompson, D. Hollander, and R. Tobin. Namespaces in XML 1.0 (third edition). W3C recommendation, W3C, Dec. 2009.
http://www.w3.org/TR/2009/REC-xml-names-20091208/.
[17] A. Miles and S. Bechhofer. SKOS simple knowledge organization system reference. W3C recommendation, W3C, Aug. 2009.
http://www.w3.org/TR/2009/REC-skos-reference-20090818/.
[18] R. Moats. Urn syntax, 1997.
[19] N. F. Noy, D. L. McGuinness, et al. Ontology development 101: A guide to
creating your first ontology, 2001.
27
Bibliography eProcurement UML conceptual model conventions
[20] J. Paoli, F. Yergeau, M. Sperberg-McQueen, T. Bray, E. Maler, and J. Cowan.
Extensible markup language (XML) 1.1 (second edition). W3C recommendation, W3C, Aug. 2006. http://www.w3.org/TR/2006/REC-xml11-20060816/.
[21] B. Parsia, P. Patel-Schneider, and B. Motik. OWL 2 web ontology language
structural specification and functional-style syntax (second edition). W3C
recommendation, W3C, Dec. 2012. http://www.w3.org/TR/2012/REC-owl2-
syntax-20121211/.
[22] P. Patel-Schneider, B. Parsia, and B. Motik. OWL 2 web ontology language
structural specification and functional-style syntax. W3C recommendation,
W3C, Oct. 2009. http://www.w3.org/TR/2009/REC-owl2-syntax-20091027/.
[23] D. Peterson, A. Malhotra, S. Gao, M. Sperberg-McQueen, P. V. Biron,
and H. Thompson. W3C xml schema definition language (XSD)
1.1 part 2: Datatypes. W3C recommendation, W3C, Apr. 2012.
http://www.w3.org/TR/2012/REC-xmlschema11-2-20120405/.
[24] PwC EU Services. D3.1 - process and methodology for core vocabularies. Deliverable, ISA programme of the European Commission, 2011.
[25] PwC EU Services. e-government core vocabularies handbook. Report, ISA
programme of the European Commission, 2015. URL https://ec.europa.
eu/isa2/library/e-government-core-vocabularies-handbook_en.
[26] E. Rescorla, R. Barnes, and S. Kent. Further Key Words for Use in RFCs to Indicate Requirement Levels. RFC 6919, Apr. 2013. URL https://rfc-editor.
org/rfc/rfc6919.txt.
[27] D. Reynolds. The organization ontology. W3C recommendation, W3C, Jan.
2014. http://www.w3.org/TR/2014/REC-vocab-org-20140116/.
[28] P. Saint-Andre and J. Klensin. Uniform resource names (urns). Internet Engineering Task Force (IETF), RFC, 8141, 2017.
[29] R. Studer, V. R. Benjamins, and D. Fensel. Knowledge engineering: principles
and methods. Data & knowledge engineering, 25(1-2):161–197, 1998.
[30] D. Wood, R. Cyganiak, and M. Lanthaler. RDF 1.1 concepts
and abstract syntax. W3C recommendation, W3C, Feb. 2014.
http://www.w3.org/TR/2014/REC-rdf11-concepts-20140225/.







