= *1 INTRODUCTION*
This report is the result of preliminary work on the specification of an e-procurement ontology commissioned by the Publications Office of the EU. The work was performed by PwC together with a working group of stakeholders in the period between December 2016 and May 2017. The report acts as a first draft of the specification of the ontology based on a limited number of use cases as well as a starting point for the further development of the ontology by the working group in 2017 and 2018.

== *1.1 Context and problem statement*

Procurement data has been identified as data with a high reuse potential. Following the paraigm of "data as a service", making this data available in machine-readable formats is required in order to maximise its reuse.
Given the increasing importance of data standards for e-procurement, a number of initiatives driven by the public sector, industry, and academia have been started in recent years. Some have grown organically, while others are the result of standardisation work. The vocabularies and the semantics that they introduce, the phases of public procurement that they cover, and the technologies that they use, all differ. These differences hamper data interoperability and reuse. This creates the need for a common data standard for publishing procurement data, hence allowing data from different sources to be easily accessed and linked, and consequently reused.

== *1.2 Proposed solution*

The objective of the e-procurement ontology is to act as a common standard on the conceptual level, based on consensus by the main stakeholders and designed to encompass the major requirements of the e-procurement process in conformance with the Directives 2014/23/EU2, 2014/24/EU3, 2014/25/EU4 and 2014/55/EU5.

== *1.3 Scope*

The work on the development of the e-procurement ontology followed work in 2016 that led to a report, the D04.07 Report on policy support for e-procurement: e-procurement ontology, dated 20 September 20166, which is referred to in this document as the landscaping report.
In the current preliminary phase, covered by these specifications and the project charter, an initial version of the ontology and the underlying conceptual model is developed for three use cases. Using these three uses cases as examples, the specifications document shows step-by step how the ontology is to be developed and how the problems mentioned above are to be overcome. The specification shows the conceptual model (see Figure 4: Conceptual data model of this document) and its presentation in OWL (of which an extract is available in Annex IV).
Taking into consideration the document “Process and methodology for developing semantic agreements”, the work identifies and gives examples of each step of the process for creating the e-procurement ontology, clearly specifying the roles of the different actors and the input required from them within the timeline of creating the ontology.