= *8 LESSONS LEARNED*

During the execution of the methodology based on 3 use cases, some challenges were identified, which should be taken into account in the next phase of the project.

== *8.1 Lessons related to the definition of use cases*

* Making use cases reflect a realistic scenario - checking all assumptions, if necessary asking for outside review
* Creating a description that outlines the main aspects of the use case - making sure a reader understands what is being done and why
* Avoiding too many assumption and pre-conditions - only mentioning things that can be reasonably expected
* Finding the right level of detail for the description of the flow providing a clear description of the elements that are relevant - making use cases more realistic with the use of invented names for persons (Bob, Alice) and organisations

== *8.2 Lessons related to the definition of requirements and identification of classes, properties and relationships*

* Generalising the elements in the use case by identifying the kinds of things and organisations that play a role in the use case
* Describing in some detail what characteristics the elements should have and what the semantics of relationships are
* Merging similar elements across use cases by looking for similarities in the role that elements play in the process

== *8.3 Lessons in finding related elements in existing solutions*

* Choosing between terms from existing ontologies having the same reusability level
* Finding a URL which identifies a concept coming from a XML scheme allowing concepts to be effectively used as linked data. An example of XML scheme which is not providing URL but URN in this case is UBL.

== *8.4 Lessons in developing the conceptual model*

* Verifying that classes and properties in the conceptual model represent existing, real world elements (e.g. an existing system or document)
* Deciding whether creating a new class is required or adapting the definition (e.g. the definition of economic operator should include the consortium) or creating a new property can be alternative solutions.

== *8.5 Lessons in defining the OWL ontology*

* Finding data to test the appropriateness of the ontology in real-life environments