= *Annex IV OWL EXTRACT*

An extract of the OWL file (i.e eproc_v0.5) was added under this annex. The entire OWL file can be consulted or downloaded from GitHub: https://github.com/eprocurementontology/eprocurementontology/wiki

[source,OWL]
--
<?xml version="1.0"?>
<rdf:RDF xmlns="http://data.europa.eu/eproc/ontology#"
 xml:base="http://data.europa.eu/eproc/ontology"
 xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
 xmlns:terms="http://purl.org/dc/terms/"
 xmlns:owl="http://www.w3.org/2002/07/owl#"
 xmlns:xml="http://www.w3.org/XML/1998/namespace"
 xmlns:xsd="http://www.w3.org/2001/XMLSchema#"
 xmlns:skos="http://www.w3.org/2004/02/skos/core#"
 xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"
 xmlns:vann="http://purl.org/vocab/vann/"
 xmlns:foaf="http://xmlns.com/foaf/0.1/"
 xmlns:dc="http://purl.org/dc/elements/1.1/"
 xmlns:fibo-fnd-pas-pas="http://www.omg.org/spec/EDMC-FIBO/FND/ProductsAndServices/ProductsAndServices/">
 <owl:Ontology rdf:about="http://data.europa.eu/eproc/ontology#">
 <terms:creator xml:lang="en">Publications Office</terms:creator>
 <rdfs:comment xml:lang="en">An ontology to describe the information 
model of the e-procurement process</rdfs:comment>
 <owl:versionInfo xml:lang="en">0.1</owl:versionInfo>
 <skos:editorialNote xml:lang="en">- The e-procurement ontology reuses the 
property names from existing ontologies:
List TBD</skos:editorialNote>
 
<vann:preferredNamespacePrefix>eproc</vann:preferredNamespacePrefix>
 <skos:historyNote xml:lang="en">* 0.1 *
 - added the following concepts:
 -</skos:historyNote>
 <rdfs:seeAlso 
rdf:resource="https://joinup.ec.europa.eu/asset/eprocurementontology"/>
 <rdfs:label xml:lang="en">e-procurement ontology</rdfs:label>
 </owl:Ontology>
 
D02.01: Specification of the process and methodology to develop the eProcurement 
ontology with initial draft of the eProcurement Ontology for 3 use cases
Page 69 of 70
 <!--
 ///////////////////////////////////////////////////////////////////////////////////////
 //
 // Datatypes
 //
 ///////////////////////////////////////////////////////////////////////////////////////
 -->
 <!-- http://www.w3.org/2001/XMLSchema#date -->
 <rdfs:Datatype rdf:about="http://www.w3.org/2001/XMLSchema#date"/>
 
 <!--
 ///////////////////////////////////////////////////////////////////////////////////////
 //
 // Object Properties
 //
 ///////////////////////////////////////////////////////////////////////////////////////
 -->
 <!-- http://data.europa.eu/eproc/ontology#chargesFor -->
 <owl:ObjectProperty 
rdf:about="http://data.europa.eu/eproc/ontology#chargesFor">
 <rdfs:domain 
rdf:resource="http://data.europa.eu/eproc/ontology#Invoice"/>
 <rdfs:range 
rdf:resource="http://data.europa.eu/eproc/ontology#ProductOrServiceOrWork"/>
 <rdfs:comment xml:lang="en">A Product Or Service Or Work for which an 
Invoice is issued</rdfs:comment>
 <rdfs:label xml:lang="en">charges for</rdfs:label>
 </owl:ObjectProperty>
 <!-- http://data.europa.eu/eproc/ontology#hasCurrency -->
 <owl:ObjectProperty 
rdf:about="http://data.europa.eu/eproc/ontology#hasCurrency">
 <rdfs:domain 
rdf:resource="http://data.europa.eu/eproc/ontology#MonetaryValue"/>
D02.01: Specification of the process and methodology to develop the eProcurement 
ontology with initial draft of the eProcurement Ontology for 3 use cases
Page 70 of 70
 <rdfs:range 
rdf:resource="http://data.europa.eu/eproc/ontology#Currency"/>
 <rdfs:comment xml:lang="en">A kind of money. Use of values from the MDR 
Currency NAL is mandatory.</rdfs:comment>
 <rdfs:label xml:lang="en">has currency</rdfs:label>
 </owl:ObjectProperty>
 
 <!-- http://data.europa.eu/eproc/ontology#hasNetValue -->
 <owl:ObjectProperty 
rdf:about="http://data.europa.eu/eproc/ontology#hasNetValue">
 <rdfs:domain 
rdf:resource="http://data.europa.eu/eproc/ontology#Payment"/>
 <rdfs:domain rdf:resource="http://www.omg.org/spec/EDMC-FIBO/FND/Agreements/Contracts/Contract"/>
 <rdfs:range 
rdf:resource="http://data.europa.eu/eproc/ontology#MonetaryValue"/>
 <rdfs:comment xml:lang="en">An amount of money, exclusive of 
VAT</rdfs:comment>
 <rdfs:label xml:lang="en">has net value</rdfs:label>
 </owl:ObjectProperty>
 
 <!-- http://data.europa.eu/eproc/ontology#hasVAT -->
 <owl:ObjectProperty 
rdf:about="http://data.europa.eu/eproc/ontology#hasVAT">
 <rdfs:domain 
rdf:resource="http://data.europa.eu/eproc/ontology#Invoice"/>
 <rdfs:domain 
rdf:resource="http://data.europa.eu/eproc/ontology#Payment"/>
 <rdfs:range 
rdf:resource="http://data.europa.eu/eproc/ontology#MonetaryValue"/>
 <rdfs:comment xml:lang="en">An amount of money that is the Value Added 
Tax</rdfs:comment>
 <rdfs:label xml:lang="en">has VAT</rdfs:label>
 </owl:ObjectProperty>
 
--